version: "3"

services:
  app:
    image: mavedb-api/mavedb-api:dev
    build:
      context: .
      target: application
    command: bash -c "uvicorn mavedb.server_main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - redis
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_SSL: "false"
    ports:
      - "8002:8000"
    volumes:
      - .:/code

  worker:
    image: mavedb-api/mavedb-worker:dev
    build:
      context: .
      target: worker
    command: bash -c "arq mavedb.worker.WorkerSettings --watch ./src"
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_SSL: "false"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    env_file:
      - settings/.env.dev
    ports:
      - "5434:5432"
    volumes:
      - mavedb-data-dev:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    env_file:
      - settings/.env.dev
    ports:
      - "6381:6379"
    volumes:
      - mavedb-redis-dev:/data

#  rabbitmq:
#    image: rabbitmq:3.8.3
#    ports:
#      - "5673:5672"

volumes:
  mavedb-data-dev:
  mavedb-redis-dev:
