FROM ubuntu:latest
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip python3-psycopg2 postgresql libpq-dev
WORKDIR /code

# Install Python packages.
COPY LICENSE README.md pyproject.toml ./
COPY src/ ./src/
COPY tests/ ./tests/
COPY mypy_stubs ./mypy_stubs/

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade .[dev,server]
RUN useradd testuser -d /code 

RUN --network=none su testuser -c pytest
