version: "3"

services:
  app:
    image: mavedb-api/mavedb-api:dev
    build:
      context: .
      target: application
    command: bash -c "uvicorn mavedb.server_main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - redis
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_SSL: "false"
      LOG_CONFIG: dev
    ports:
      - "8002:8000"
    volumes:
      - .:/code
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

  worker:
    image: mavedb-api/mavedb-worker:dev
    build:
      context: .
      target: worker
    command: bash -c "arq mavedb.worker.WorkerSettings --watch ./src"
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: redis
      REDIS_PORT: 6379
      REDIS_SSL: "false"
      LOG_CONFIG: dev
    volumes:
      - .:/code
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo
    depends_on:
      - db
      - redis

  dcd-mapping:
    build: ../dcd_mapping
    image: dcd-mapping:dev
    command: bash -c "uvicorn api.server_main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
      - seqrepo
    env_file:
      - settings/.env.dev
    ports:
      - "8004:8000"
    volumes:
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

  cdot-rest:
    build: ../cdot_rest
    image: cdot-rest:dev
    command: bash -c "gunicorn cdot_rest.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - settings/.env.dev
    depends_on:
      - redis
      - seqrepo
    ports:
      - "8006:8000"
    volumes:
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

  db:
    image: postgres:14
    env_file:
      - settings/.env.dev
    ports:
      - "5434:5432"
    volumes:
      - mavedb-data-dev:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    env_file:
      - settings/.env.dev
    ports:
      - "6381:6379"
    volumes:
      - mavedb-redis-dev:/data

  seqrepo:
    image: biocommons/seqrepo:2024-12-20
    volumes:
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

volumes:
  mavedb-data-dev:
  mavedb-redis-dev:
  mavedb-seqrepo-dev:
