from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.utils import get_openapi

from app.routers import experiment_sets, experiments, reference_genomes, scoresets, search, target_genes

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.include_router(experiment_sets.router)
app.include_router(experiments.router)
app.include_router(reference_genomes.router)
app.include_router(scoresets.router)
app.include_router(search.router)
app.include_router(target_genes.router)


def customize_openapi_schema():
    title = 'MaveDB API'
    version = '2.0a1'
    openapi_schema = get_openapi(
       title=title,
       version=version,
       routes=app.routes
    )
    openapi_schema['info'] = {
       'title': title,
       'version': version,
       'description': '''MaveDB is a public repository for datasets from Multiplexed Assays of Variant Effect (MAVEs), such
           as those generated by deep mutational scanning (DMS) or massively parallel reporter assay (MPRA)
           experiments.''',
       # 'termsOfService': 'url',
       'contact': {
           'name': 'MavaDB/CAVA software group',
           'url': 'https://github.com/VariantEffect/mavedb/issues',
           'email': 'rubin.a@wehi.edu.au'
       },
       'license': {
           'name': 'License TBD',
           'url': 'https://www.apache.org/licenses/LICENSE-2.0.html'
       }
    }
    app.openapi_schema = openapi_schema
    return app.openapi_schema


customize_openapi_schema()
