from typing import Any, Iterator, Optional
from biocommons.seqrepo.fastadir.bases import BaseReader, BaseWriter

class FastaDir(BaseReader, BaseWriter):
    def __init__(
        self, root_dir: str, writeable: bool = False, check_same_thread: bool = True, fd_cache_size: int = 0
    ) -> None: ...
    def __del__(self) -> None: ...
    def __contains__(self, seq_id: str) -> bool: ...
    def __iter__(self) -> Iterator[dict]: ...
    def __len__(self) -> int: ...
    def commit(self) -> None: ...
    def fetch(self, seq_id: str, start: Optional[int] = None, end: Optional[int] = None) -> str: ...
    def fetch_seqinfo(self, seq_id: str) -> dict: ...
    def schema_version(self) -> Optional[int]: ...
    def stats(self) -> dict: ...
    def store(self, seq_id: str, seq: str) -> str: ...
    def _fetch_one(self, sql: str, params: Any = ...) -> Any: ...
    def _upgrade_db(self) -> None: ...
    def _dump_aliases(self) -> None: ...
