"""add score calibration table

Revision ID: 002f6f9ec7ac
Revises: 019eb75ad9ae
Create Date: 2025-10-08 08:59:10.563528

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "002f6f9ec7ac"
down_revision = "019eb75ad9ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score_calibrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("urn", sa.String(length=64), nullable=True),
        sa.Column("score_set_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("research_use_only", sa.Boolean(), nullable=False),
        sa.Column("primary", sa.Boolean(), nullable=False),
        sa.Column("investigator_provided", sa.Boolean(), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("baseline_score", sa.Float(), nullable=True),
        sa.Column("baseline_score_description", sa.String(), nullable=True),
        sa.Column("functional_ranges", postgresql.JSONB(astext_type=sa.Text(), none_as_null=True), nullable=True),
        sa.Column("calibration_metadata", postgresql.JSONB(astext_type=sa.Text(), none_as_null=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("modified_by_id", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("modification_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["score_set_id"],
            ["scoresets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score_calibration_publication_identifiers",
        sa.Column("score_calibration_id", sa.Integer(), nullable=False),
        sa.Column("publication_identifier_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "thresholds",
                "classifications",
                "methods",
                name="scorecalibrationrelation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_identifier_id"],
            ["publication_identifiers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["score_calibration_id"],
            ["score_calibrations.id"],
        ),
        sa.PrimaryKeyConstraint("score_calibration_id", "publication_identifier_id", "relation"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("score_calibration_publication_identifiers")
    op.drop_table("score_calibrations")
    # ### end Alembic commands ###
