"""add external links property to experiments

Revision ID: 00dab0f5f498
Revises: b22b450d409c
Create Date: 2025-12-16 12:06:15.265947

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "00dab0f5f498"
down_revision = "b22b450d409c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiments",
        sa.Column("external_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiments", "external_links")
    # ### end Alembic commands ###
