"""rename_tax_id_to_code

Revision ID: 019eb75ad9ae
Revises: b29bbfb2a13a
Create Date: 2025-08-20 16:21:15.872816

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "019eb75ad9ae"
down_revision = "0b29eefbe1dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taxonomies", "tax_id", new_column_name="code", existing_type=sa.Integer(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taxonomies", "code", new_column_name="tax_id", existing_type=sa.Integer(), existing_nullable=False)
    # ### end Alembic commands ###
