"""Target category enum

Revision ID: 03c7124c33e1
Revises: 2b6f40ea2fb6
Create Date: 2024-11-01 11:27:03.609116

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03c7124c33e1"
down_revision = "2b6f40ea2fb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "target_genes",
        "category",
        type_=sa.Enum(
            "protein_coding",
            "other_noncoding",
            "regulatory",
            name="targetcategory",
            native_enum=False,
            create_constraint=True,
            length=32,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "target_genes",
        "category",
        type_=sa.String(),
        existing_type=sa.Enum(
            "protein_coding",
            "other_noncoding",
            "regulatory",
            name="targetcategory",
            native_enum=False,
            create_constraint=True,
            length=32,
        ),
    )
    # ### end Alembic commands ###
