"""rename functional ranges to functional classifications, add class_ to model, rename classification to functional_classification

Revision ID: 0520dfa9f2db
Revises: c770fa9e6e58
Create Date: 2025-11-18 18:51:33.107952

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0520dfa9f2db"
down_revision = "c770fa9e6e58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_calibration_functional_classifications",
        "classification",
        new_column_name="functional_classification",
        type_=sa.Enum(
            "normal", "abnormal", "not_specified", name="functionalclassification", native_enum=False, length=32
        ),
        nullable=False,
    )
    op.add_column("score_calibration_functional_classifications", sa.Column("class_", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_calibration_functional_classifications",
        "functional_classification",
        new_column_name="classification",
        type_=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.drop_column("score_calibration_functional_classifications", "class_")
    # ### end Alembic commands ###
