"""add acmg classification and functional classification tables

Revision ID: 16beeb593513
Revises: b22b450d409c
Create Date: 2025-11-17 11:46:38.276980

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "16beeb593513"
down_revision = "b22b450d409c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acmg_classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "criterion",
            sa.Enum(
                "PVS1",
                "PS1",
                "PS2",
                "PS3",
                "PS4",
                "PM1",
                "PM2",
                "PM3",
                "PM4",
                "PM5",
                "PM6",
                "PP1",
                "PP2",
                "PP3",
                "PP4",
                "PP5",
                "BA1",
                "BS1",
                "BS2",
                "BS3",
                "BS4",
                "BP1",
                "BP2",
                "BP3",
                "BP4",
                "BP5",
                "BP6",
                "BP7",
                name="acmgcriterion",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "evidence_strength",
            sa.Enum(
                "VERY_STRONG",
                "STRONG",
                "MODERATE_PLUS",
                "MODERATE",
                "SUPPORTING",
                name="strengthofevidenceprovided",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("modification_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score_calibration_functional_classifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calibration_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "normal", "abnormal", "not_specified", name="functionalclassification", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("range", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("inclusive_lower_bound", sa.Boolean(), nullable=True),
        sa.Column("inclusive_upper_bound", sa.Boolean(), nullable=True),
        sa.Column("oddspaths_ratio", sa.Float(), nullable=True),
        sa.Column("positive_likelihood_ratio", sa.Float(), nullable=True),
        sa.Column("acmg_classification_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acmg_classification_id"],
            ["acmg_classifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["score_calibrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score_calibration_functional_classification_variants",
        sa.Column("functional_classification_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["functional_classification_id"],
            ["score_calibration_functional_classifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
        ),
        sa.PrimaryKeyConstraint("functional_classification_id", "variant_id"),
    )
    op.alter_column("score_calibrations", "functional_ranges", new_column_name="functional_ranges_deprecated_json")
    op.create_index(op.f("ix_score_calibrations_created_by_id"), "score_calibrations", ["created_by_id"], unique=False)
    op.create_index(
        op.f("ix_score_calibrations_modified_by_id"), "score_calibrations", ["modified_by_id"], unique=False
    )
    op.create_index(op.f("ix_score_calibrations_urn"), "score_calibrations", ["urn"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_score_calibrations_urn"), table_name="score_calibrations")
    op.drop_index(op.f("ix_score_calibrations_modified_by_id"), table_name="score_calibrations")
    op.drop_index(op.f("ix_score_calibrations_created_by_id"), table_name="score_calibrations")
    op.drop_table("score_calibration_functional_classification_variants")
    op.drop_table("score_calibration_functional_classifications")
    op.drop_table("acmg_classifications")
    # ### end Alembic commands ###
