"""Controlled keyword Gene Ontology

Revision ID: 18b6d81c045e
Revises: c404b6719110
Create Date: 2025-03-14 19:13:01.554046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b6d81c045e'
down_revision = 'c404b6719110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlled_keywords', sa.Column('accession', sa.String(), nullable=True))

    # TODO: Will modify this part when we get the final GO terms.
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, accession, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Mechanism', 'Other', NULL, NULL, False, 'The Gene Ontology (GO) is a structured, standardized representation of biological knowledge.', NOW(), NOW())"""
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controlled_keywords', 'accession')
    # ### end Alembic commands ###
