"""make index on contributors unique

Revision ID: 1cee01c42909
Revises: 76e1e55bc5c1
Create Date: 2024-09-03 09:53:21.635751

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1cee01c42909"
down_revision = "1d4933b4b6f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contributors_orcid_id", table_name="contributors")
    op.create_index(op.f("ix_contributors_orcid_id"), "contributors", ["orcid_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contributors_orcid_id"), table_name="contributors")
    op.create_index("ix_contributors_orcid_id", "contributors", ["orcid_id"], unique=False)
    # ### end Alembic commands ###
