"""Add functional consequence

Revision ID: 1e08b947679d
Revises: f5a72192fafd
Create Date: 2025-09-17 11:15:52.091271

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e08b947679d"
down_revision = "f5a72192fafd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mapped_variants", sa.Column("vep_functional_consequence", sa.String(), nullable=True))
    op.add_column("mapped_variants", sa.Column("vep_access_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mapped_variants", "vep_access_date")
    op.drop_column("mapped_variants", "vep_functional_consequence")
    # ### end Alembic commands ###
