"""pre_mapped_vrs_columns

Revision ID: 29935f9d7f0e
Revises: c4b18d0f7a92
Create Date: 2026-09-18 11:33:50.530384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29935f9d7f0e'
down_revision = 'c4b18d0f7a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('pre_mapped_vrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('variants', sa.Column('pre_mapped_vrs_digest', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('pre_mapped_vrs_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_variants_pre_mapped_vrs_digest'), 'variants', ['pre_mapped_vrs_digest'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_pre_mapped_vrs_digest'), table_name='variants')
    op.drop_column('variants', 'pre_mapped_vrs_version')
    op.drop_column('variants', 'pre_mapped_vrs_digest')
    op.drop_column('variants', 'pre_mapped_vrs')
    # ### end Alembic commands ###
