"""Consolidate Publication Identifier DOIs

Revision ID: 2c8d7e2bf2fe
Revises: 8bcb2b4edc60
Create Date: 2024-05-16 13:06:05.561411

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import Session
from mavedb.models.publication_identifier import PublicationIdentifier


# revision identifiers, used by Alembic.
revision = "2c8d7e2bf2fe"
down_revision = "8bcb2b4edc60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication_identifiers", sa.Column("doi", sa.String(), nullable=True))

    conn = op.get_bind()
    session = Session(bind=conn)

    # Default to using the publication doi if it exists, otherwise use the preprint doi.
    existing_publications = session.execute(sa.select(PublicationIdentifier)).scalars()
    for publication in existing_publications:
        publication.doi = publication.publication_doi if publication.publication_doi else publication.preprint_doi

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: In a future downgrade when dropping fields, run something like this to restore the dropped doi fields.
    # conn = op.get_bind()
    # session = Session(bind=conn)

    # # If the article is a preprint, use the DOI to set its preprint doi property. Otherwise, set the publication doi property
    # existing_publications = session.execute(sa.select(PublicationIdentifier)).all()
    # for publication in existing_publications:
    #     if publication.publication_journal == "Preprint":
    #         publication.preprint_doi = publication.doi
    #         publication.publication_doi = None
    #     else:
    #         publication.preprint_doi = None
    #         publication.publication_doi = publication.doi
    #
    # sesssion.commit()

    op.drop_column("publication_identifiers", "doi")
    # ### end Alembic commands ###
