"""Consolidate Publication Identifier DOIs

Revision ID: 2c8d7e2bf2fe
Revises: 8bcb2b4edc60
Create Date: 2024-05-16 13:06:05.561411

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c8d7e2bf2fe"
down_revision = "8bcb2b4edc60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication_identifiers", sa.Column("doi", sa.String(), nullable=True))
    op.execute("UPDATE publication_identifiers SET doi = COALESCE(publication_doi, preprint_doi)")

    op.drop_constraint("publication_doi_preprint_doi_not_null_constraint", table_name="publication_identifiers")
    op.drop_column("publication_identifiers", "publication_doi")
    op.drop_column("publication_identifiers", "preprint_doi")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication_identifiers", sa.Column("publication_doi", sa.String(), nullable=True))
    op.add_column("publication_identifiers", sa.Column("preprint_doi", sa.String(), nullable=True))

    op.execute("UPDATE publication_identifiers SET publication_doi = doi WHERE publication_journal <> 'Preprint'")
    op.execute("UPDATE publication_identifiers SET preprint_doi = doi WHERE publication_journal = 'Preprint'")

    op.create_check_constraint(
        "publication_doi_preprint_doi_not_null_constraint",
        table_name="publication_identifiers",
        condition="(publication_doi IS NULL) <> (preprint_doi IS NULL)",
    )
    op.drop_column("publication_identifiers", "doi")
    # ### end Alembic commands ###
