"""clinvar variant table

Revision ID: 34026092c7f8
Revises: e8a3b5d8f885
Create Date: 2025-01-28 21:48:42.532346

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34026092c7f8"
down_revision = "e8a3b5d8f885"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinvar_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("allele_id", sa.Integer(), nullable=False),
        sa.Column("gene_symbol", sa.String(), nullable=False),
        sa.Column("clinical_significance", sa.String(), nullable=False),
        sa.Column("clinical_review_status", sa.String(), nullable=False),
        sa.Column("clinvar_db_version", sa.String(), nullable=False),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("modification_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clinvar_variants_allele_id"), "clinvar_variants", ["allele_id"], unique=False)
    op.add_column("mapped_variants", sa.Column("clinvar_variant_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_mapped_variants_clinvar_variant_id"), "mapped_variants", ["clinvar_variant_id"], unique=False
    )
    op.create_foreign_key(
        "mapped_variant_clinvar_variant_id_foreign_key_constraint",
        "mapped_variants",
        "clinvar_variants",
        ["clinvar_variant_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("mapped_variants_clinvar_variant_foreign_key_constraint", "mapped_variants", type_="foreignkey")
    op.drop_index(op.f("ix_mapped_variants_clinvar_variant_id"), table_name="mapped_variants")
    op.drop_column("mapped_variants", "clinvar_variant_id")
    op.drop_index(op.f("ix_clinvar_variants_allele_id"), table_name="clinvar_variants")
    op.drop_table("clinvar_variants")
    # ### end Alembic commands ###
