"""empty message

Revision ID: 369b839e8ffd
Revises: 
Create Date: 2022-02-23 14:26:24.798866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '369b839e8ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('metadata_uniprotidentifier_identifier_14028ac2_like', table_name='metadata_uniprotidentifier')
    op.drop_table('metadata_uniprotidentifier')
    op.drop_index('dataset_experimentset_pubmed_ids_experimentset_id_8b042599', table_name='dataset_experimentset_pubmed_ids')
    op.drop_index('dataset_experimentset_pubmed_ids_pubmedidentifier_id_b112c80c', table_name='dataset_experimentset_pubmed_ids')
    op.drop_table('dataset_experimentset_pubmed_ids')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('reversion_version_content_type_id_7d0ff25c', table_name='reversion_version')
    op.drop_index('reversion_version_revision_id_af9f6a9d', table_name='reversion_version')
    op.drop_table('reversion_version')
    op.drop_index('dataset_scoreset_doi_ids_doiidentifier_id_49ffeab1', table_name='dataset_scoreset_doi_ids')
    op.drop_index('dataset_scoreset_doi_ids_scoreset_id_b81a5078', table_name='dataset_scoreset_doi_ids')
    op.drop_table('dataset_scoreset_doi_ids')
    op.drop_index('tracking_visitor_session_key_8cd35282_like', table_name='tracking_visitor')
    op.drop_index('tracking_visitor_user_id_68f9235e', table_name='tracking_visitor')
    op.drop_table('tracking_visitor')
    op.drop_table('genome_wildtypesequence')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index('genome_targetgene_ensembl_id_id_cef7ac83', table_name='genome_targetgene')
    op.drop_index('genome_targetgene_refseq_id_id_c212e2df', table_name='genome_targetgene')
    op.drop_index('genome_targetgene_uniprot_id_id_1b5cab1b', table_name='genome_targetgene')
    op.drop_table('genome_targetgene')
    op.drop_index('metadata_ensemblidentifier_identifier_a56ead60_like', table_name='metadata_ensemblidentifier')
    op.drop_table('metadata_ensemblidentifier')
    op.drop_index('genome_referencemap_genome_id_6bccb458', table_name='genome_referencemap')
    op.drop_index('genome_referencemap_target_id_5b68b9e1', table_name='genome_referencemap')
    op.drop_table('genome_referencemap')
    op.drop_index('tracking_pageview_visitor_id_a78682e5', table_name='tracking_pageview')
    op.drop_index('tracking_pageview_visitor_id_a78682e5_like', table_name='tracking_pageview')
    op.drop_table('tracking_pageview')
    op.drop_index('dataset_scoreset_pubmed_ids_pubmedidentifier_id_ba5197ac', table_name='dataset_scoreset_pubmed_ids')
    op.drop_index('dataset_scoreset_pubmed_ids_scoreset_id_d5cccd08', table_name='dataset_scoreset_pubmed_ids')
    op.drop_table('dataset_scoreset_pubmed_ids')
    op.drop_index('variant_variant_scoreset_id_1bb9e259', table_name='variant_variant')
    op.drop_index('variant_variant_urn_c3db4a8b_like', table_name='variant_variant')
    op.drop_table('variant_variant')
    op.drop_table('accounts_profile')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('social_auth_usersocialauth_user_id_17d28448', table_name='social_auth_usersocialauth')
    op.drop_table('social_auth_usersocialauth')
    op.drop_index('dataset_experimentset_created_by_id_d91fa9d1', table_name='dataset_experimentset')
    op.drop_index('dataset_experimentset_modified_by_id_cdcd274f', table_name='dataset_experimentset')
    op.drop_index('dataset_experimentset_urn_f732d47b_like', table_name='dataset_experimentset')
    op.drop_table('dataset_experimentset')
    op.drop_table('django_migrations')
    op.drop_index('metadata_keyword_text_6c84ecc5_like', table_name='metadata_keyword')
    op.drop_table('metadata_keyword')
    op.drop_index('social_auth_partial_timestamp_50f2119f', table_name='social_auth_partial')
    op.drop_index('social_auth_partial_token_3017fea3', table_name='social_auth_partial')
    op.drop_index('social_auth_partial_token_3017fea3_like', table_name='social_auth_partial')
    op.drop_table('social_auth_partial')
    op.drop_table('manager_userrole')
    op.drop_index('dataset_experiment_pubmed_ids_experiment_id_e058be6c', table_name='dataset_experiment_pubmed_ids')
    op.drop_index('dataset_experiment_pubmed_ids_pubmedidentifier_id_9262b233', table_name='dataset_experiment_pubmed_ids')
    op.drop_table('dataset_experiment_pubmed_ids')
    op.drop_table('main_news')
    op.drop_index('reversion_revision_date_created_96f7c20c', table_name='reversion_revision')
    op.drop_index('reversion_revision_user_id_17095f45', table_name='reversion_revision')
    op.drop_table('reversion_revision')
    op.drop_index('guardian_groupobjectpermission_content_type_id_7ade36b8', table_name='guardian_groupobjectpermission')
    op.drop_index('guardian_groupobjectpermission_group_id_4bbbfb62', table_name='guardian_groupobjectpermission')
    op.drop_index('guardian_groupobjectpermission_permission_id_36572738', table_name='guardian_groupobjectpermission')
    op.drop_table('guardian_groupobjectpermission')
    op.drop_index('metadata_ensembloffset_identifier_id_33296b8d', table_name='metadata_ensembloffset')
    op.drop_index('metadata_ensembloffset_target_id_f79b10d6', table_name='metadata_ensembloffset')
    op.drop_table('metadata_ensembloffset')
    op.drop_index('genome_referencegenome_genome_id_id_93c131c0', table_name='genome_referencegenome')
    op.drop_table('genome_referencegenome')
    op.drop_index('dataset_scoreset_created_by_id_8e4fd7d0', table_name='dataset_scoreset')
    op.drop_index('dataset_scoreset_experiment_id_f6f4acd5', table_name='dataset_scoreset')
    op.drop_index('dataset_scoreset_licence_id_fe8c45ec', table_name='dataset_scoreset')
    op.drop_index('dataset_scoreset_modified_by_id_d3e6e918', table_name='dataset_scoreset')
    op.drop_index('dataset_scoreset_urn_505317a9_like', table_name='dataset_scoreset')
    op.drop_table('dataset_scoreset')
    op.drop_index('dataset_experimentset_doi_ids_doiidentifier_id_5497853c', table_name='dataset_experimentset_doi_ids')
    op.drop_index('dataset_experimentset_doi_ids_experimentset_id_75a608a7', table_name='dataset_experimentset_doi_ids')
    op.drop_table('dataset_experimentset_doi_ids')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index('genome_genomicinterval_reference_map_id_99a3ba00', table_name='genome_genomicinterval')
    op.drop_table('genome_genomicinterval')
    op.drop_index('social_auth_code_code_a2393167', table_name='social_auth_code')
    op.drop_index('social_auth_code_code_a2393167_like', table_name='social_auth_code')
    op.drop_index('social_auth_code_timestamp_176b341f', table_name='social_auth_code')
    op.drop_table('social_auth_code')
    op.drop_table('dataset_publicdatasetcounter')
    op.drop_index('guardian_userobjectpermission_content_type_id_2e892405', table_name='guardian_userobjectpermission')
    op.drop_index('guardian_userobjectpermission_permission_id_71807bfc', table_name='guardian_userobjectpermission')
    op.drop_index('guardian_userobjectpermission_user_id_d5c1e964', table_name='guardian_userobjectpermission')
    op.drop_table('guardian_userobjectpermission')
    op.drop_index('main_licence_short_name_f9b67fee_like', table_name='main_licence')
    op.drop_table('main_licence')
    op.drop_index('metadata_genomeidentifier_identifier_cbbf28e9_like', table_name='metadata_genomeidentifier')
    op.drop_table('metadata_genomeidentifier')
    op.drop_index('dataset_experiment_sra_ids_experiment_id_aa564776', table_name='dataset_experiment_sra_ids')
    op.drop_index('dataset_experiment_sra_ids_sraidentifier_id_23618d15', table_name='dataset_experiment_sra_ids')
    op.drop_table('dataset_experiment_sra_ids')
    op.drop_table('main_siteinformation')
    op.drop_index('metadata_refseqoffset_identifier_id_5cfb09d5', table_name='metadata_refseqoffset')
    op.drop_index('metadata_refseqoffset_target_id_79a5ae10', table_name='metadata_refseqoffset')
    op.drop_table('metadata_refseqoffset')
    op.drop_index('dataset_experimentset_sra_ids_experimentset_id_a234e961', table_name='dataset_experimentset_sra_ids')
    op.drop_index('dataset_experimentset_sra_ids_sraidentifier_id_0095167a', table_name='dataset_experimentset_sra_ids')
    op.drop_table('dataset_experimentset_sra_ids')
    op.drop_index('dataset_experiment_created_by_id_32ef8eba', table_name='dataset_experiment')
    op.drop_index('dataset_experiment_experimentset_id_f120411e', table_name='dataset_experiment')
    op.drop_index('dataset_experiment_modified_by_id_988337ee', table_name='dataset_experiment')
    op.drop_index('dataset_experiment_urn_03f5d16c_like', table_name='dataset_experiment')
    op.drop_table('dataset_experiment')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('dataset_scoreset_keywords_keyword_id_94742a0a', table_name='dataset_scoreset_keywords')
    op.drop_index('dataset_scoreset_keywords_scoreset_id_e3b0d5a7', table_name='dataset_scoreset_keywords')
    op.drop_table('dataset_scoreset_keywords')
    op.drop_index('metadata_refseqidentifier_identifier_978feb13_like', table_name='metadata_refseqidentifier')
    op.drop_table('metadata_refseqidentifier')
    op.drop_table('django_content_type')
    op.drop_index('dataset_scoreset_meta_analysis_for_from_scoreset_id_65b1281f', table_name='dataset_scoreset_meta_analysis_for')
    op.drop_index('dataset_scoreset_meta_analysis_for_to_scoreset_id_767856d9', table_name='dataset_scoreset_meta_analysis_for')
    op.drop_table('dataset_scoreset_meta_analysis_for')
    op.drop_index('metadata_uniprotoffset_identifier_id_95839c5d', table_name='metadata_uniprotoffset')
    op.drop_index('metadata_uniprotoffset_target_id_ae31a417', table_name='metadata_uniprotoffset')
    op.drop_table('metadata_uniprotoffset')
    op.drop_index('dataset_experiment_keywords_experiment_id_3ad3f384', table_name='dataset_experiment_keywords')
    op.drop_index('dataset_experiment_keywords_keyword_id_da22d115', table_name='dataset_experiment_keywords')
    op.drop_table('dataset_experiment_keywords')
    op.drop_index('metadata_sraidentifier_identifier_2424ea3c_like', table_name='metadata_sraidentifier')
    op.drop_table('metadata_sraidentifier')
    op.drop_table('social_auth_nonce')
    op.drop_index('dataset_scoreset_sra_ids_scoreset_id_26803933', table_name='dataset_scoreset_sra_ids')
    op.drop_index('dataset_scoreset_sra_ids_sraidentifier_id_27c2c5b0', table_name='dataset_scoreset_sra_ids')
    op.drop_table('dataset_scoreset_sra_ids')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_index('authtoken_token_key_10f0b77e_like', table_name='authtoken_token')
    op.drop_table('authtoken_token')
    op.drop_index('dataset_experimentset_keywords_experimentset_id_e6a69065', table_name='dataset_experimentset_keywords')
    op.drop_index('dataset_experimentset_keywords_keyword_id_e82fc1b3', table_name='dataset_experimentset_keywords')
    op.drop_table('dataset_experimentset_keywords')
    op.drop_index('metadata_pubmedidentifier_identifier_9279e646_like', table_name='metadata_pubmedidentifier')
    op.drop_table('metadata_pubmedidentifier')
    op.drop_index('dataset_experiment_doi_ids_doiidentifier_id_a3a4218d', table_name='dataset_experiment_doi_ids')
    op.drop_index('dataset_experiment_doi_ids_experiment_id_10a5ada5', table_name='dataset_experiment_doi_ids')
    op.drop_table('dataset_experiment_doi_ids')
    op.drop_index('core_failedtask_user_id_1f281976', table_name='core_failedtask')
    op.drop_table('core_failedtask')
    op.drop_table('social_auth_association')
    op.drop_index('metadata_doiidentifier_identifier_a502aef6_like', table_name='metadata_doiidentifier')
    op.drop_constraint('metadata_doiidentifier_identifier_key', 'metadata_doiidentifier', type_='unique')
    op.create_index(op.f('ix_metadata_doiidentifier_id'), 'metadata_doiidentifier', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_doiidentifier_id'), table_name='metadata_doiidentifier')
    op.create_unique_constraint('metadata_doiidentifier_identifier_key', 'metadata_doiidentifier', ['identifier'])
    op.create_index('metadata_doiidentifier_identifier_a502aef6_like', 'metadata_doiidentifier', ['identifier'], unique=False)
    op.create_table('social_auth_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('issued', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lifetime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assoc_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_association_pkey'),
    sa.UniqueConstraint('server_url', 'handle', name='social_auth_association_server_url_handle_078befa2_uniq')
    )
    op.create_table('core_failedtask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modification_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=125), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('args', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exception_class', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exception_msg', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('failures', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('failures >= 0', name='core_failedtask_failures_check'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='core_failedtask_user_id_1f281976_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='core_failedtask_pkey')
    )
    op.create_index('core_failedtask_user_id_1f281976', 'core_failedtask', ['user_id'], unique=False)
    op.create_table('dataset_experiment_doi_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doiidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doiidentifier_id'], ['metadata_doiidentifier.id'], name='dataset_experiment_d_doiidentifier_id_a3a4218d_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['dataset_experiment.id'], name='dataset_experiment_d_experiment_id_10a5ada5_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experiment_doi_ids_pkey'),
    sa.UniqueConstraint('experiment_id', 'doiidentifier_id', name='dataset_experiment_doi_i_experiment_id_doiidentif_38354192_uniq')
    )
    op.create_index('dataset_experiment_doi_ids_experiment_id_10a5ada5', 'dataset_experiment_doi_ids', ['experiment_id'], unique=False)
    op.create_index('dataset_experiment_doi_ids_doiidentifier_id_a3a4218d', 'dataset_experiment_doi_ids', ['doiidentifier_id'], unique=False)
    op.create_table('metadata_pubmedidentifier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metadata_pubmedidentifier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('reference_html', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_pubmedidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_pubmedidentifier_identifier_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('metadata_pubmedidentifier_identifier_9279e646_like', 'metadata_pubmedidentifier', ['identifier'], unique=False)
    op.create_table('dataset_experimentset_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experimentset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experimentset_id'], ['dataset_experimentset.id'], name='dataset_experimentse_experimentset_id_e6a69065_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['metadata_keyword.id'], name='dataset_experimentse_keyword_id_e82fc1b3_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experimentset_keywords_pkey'),
    sa.UniqueConstraint('experimentset_id', 'keyword_id', name='dataset_experimentset_ke_experimentset_id_keyword_5caed945_uniq')
    )
    op.create_index('dataset_experimentset_keywords_keyword_id_e82fc1b3', 'dataset_experimentset_keywords', ['keyword_id'], unique=False)
    op.create_index('dataset_experimentset_keywords_experimentset_id_e6a69065', 'dataset_experimentset_keywords', ['experimentset_id'], unique=False)
    op.create_table('authtoken_token',
    sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='authtoken_token_user_id_35299eff_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('key', name='authtoken_token_pkey'),
    sa.UniqueConstraint('user_id', name='authtoken_token_user_id_key')
    )
    op.create_index('authtoken_token_key_10f0b77e_like', 'authtoken_token', ['key'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('dataset_scoreset_sra_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sraidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_sra_scoreset_id_26803933_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['sraidentifier_id'], ['metadata_sraidentifier.id'], name='dataset_scoreset_sra_sraidentifier_id_27c2c5b0_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_sra_ids_pkey'),
    sa.UniqueConstraint('scoreset_id', 'sraidentifier_id', name='dataset_scoreset_sra_ids_scoreset_id_sraidentifie_f471bebd_uniq')
    )
    op.create_index('dataset_scoreset_sra_ids_sraidentifier_id_27c2c5b0', 'dataset_scoreset_sra_ids', ['sraidentifier_id'], unique=False)
    op.create_index('dataset_scoreset_sra_ids_scoreset_id_26803933', 'dataset_scoreset_sra_ids', ['scoreset_id'], unique=False)
    op.create_table('social_auth_nonce',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salt', sa.VARCHAR(length=65), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_nonce_pkey'),
    sa.UniqueConstraint('server_url', 'timestamp', 'salt', name='social_auth_nonce_server_url_timestamp_salt_f6284463_uniq')
    )
    op.create_table('metadata_sraidentifier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metadata_sraidentifier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_sraidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_sraidentifier_identifier_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('metadata_sraidentifier_identifier_2424ea3c_like', 'metadata_sraidentifier', ['identifier'], unique=False)
    op.create_table('dataset_experiment_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['dataset_experiment.id'], name='dataset_experiment_k_experiment_id_3ad3f384_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['metadata_keyword.id'], name='dataset_experiment_k_keyword_id_da22d115_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experiment_keywords_pkey'),
    sa.UniqueConstraint('experiment_id', 'keyword_id', name='dataset_experiment_keywo_experiment_id_keyword_id_651c3adc_uniq')
    )
    op.create_index('dataset_experiment_keywords_keyword_id_da22d115', 'dataset_experiment_keywords', ['keyword_id'], unique=False)
    op.create_index('dataset_experiment_keywords_experiment_id_3ad3f384', 'dataset_experiment_keywords', ['experiment_id'], unique=False)
    op.create_table('metadata_uniprotoffset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('"offset" >= 0', name='metadata_uniprotoffset_offset_check'),
    sa.ForeignKeyConstraint(['identifier_id'], ['metadata_uniprotidentifier.id'], name='metadata_uniprotoffs_identifier_id_95839c5d_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['target_id'], ['genome_targetgene.id'], name='metadata_uniprotoffs_target_id_ae31a417_fk_genome_ta', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_uniprotoffset_pkey'),
    sa.UniqueConstraint('target_id', 'identifier_id', name='metadata_uniprotoffset_target_id_identifier_id_b7e1e30a_uniq')
    )
    op.create_index('metadata_uniprotoffset_target_id_ae31a417', 'metadata_uniprotoffset', ['target_id'], unique=False)
    op.create_index('metadata_uniprotoffset_identifier_id_95839c5d', 'metadata_uniprotoffset', ['identifier_id'], unique=False)
    op.create_table('dataset_scoreset_meta_analysis_for',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_met_from_scoreset_id_65b1281f_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['to_scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_met_to_scoreset_id_767856d9_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_meta_analysis_for_pkey'),
    sa.UniqueConstraint('from_scoreset_id', 'to_scoreset_id', name='dataset_scoreset_meta_an_from_scoreset_id_to_scor_4c916385_uniq')
    )
    op.create_index('dataset_scoreset_meta_analysis_for_to_scoreset_id_767856d9', 'dataset_scoreset_meta_analysis_for', ['to_scoreset_id'], unique=False)
    op.create_index('dataset_scoreset_meta_analysis_for_from_scoreset_id_65b1281f', 'dataset_scoreset_meta_analysis_for', ['from_scoreset_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('django_content_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_table('metadata_refseqidentifier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metadata_refseqidentifier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_refseqidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_refseqidentifier_identifier_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('metadata_refseqidentifier_identifier_978feb13_like', 'metadata_refseqidentifier', ['identifier'], unique=False)
    op.create_table('dataset_scoreset_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['metadata_keyword.id'], name='dataset_scoreset_key_keyword_id_94742a0a_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_key_scoreset_id_e3b0d5a7_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_keywords_pkey'),
    sa.UniqueConstraint('scoreset_id', 'keyword_id', name='dataset_scoreset_keywords_scoreset_id_keyword_id_73d2f813_uniq')
    )
    op.create_index('dataset_scoreset_keywords_scoreset_id_e3b0d5a7', 'dataset_scoreset_keywords', ['scoreset_id'], unique=False)
    op.create_index('dataset_scoreset_keywords_keyword_id_94742a0a', 'dataset_scoreset_keywords', ['keyword_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_permission_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('dataset_experiment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dataset_experiment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_child_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('abstract_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('method_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('urn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experimentset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_state', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='dataset_experiment_created_by_id_32ef8eba_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['experimentset_id'], ['dataset_experimentset.id'], name='dataset_experiment_experimentset_id_f120411e_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['modified_by_id'], ['auth_user.id'], name='dataset_experiment_modified_by_id_988337ee_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experiment_pkey'),
    sa.UniqueConstraint('urn', name='dataset_experiment_urn_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('dataset_experiment_urn_03f5d16c_like', 'dataset_experiment', ['urn'], unique=False)
    op.create_index('dataset_experiment_modified_by_id_988337ee', 'dataset_experiment', ['modified_by_id'], unique=False)
    op.create_index('dataset_experiment_experimentset_id_f120411e', 'dataset_experiment', ['experimentset_id'], unique=False)
    op.create_index('dataset_experiment_created_by_id_32ef8eba', 'dataset_experiment', ['created_by_id'], unique=False)
    op.create_table('dataset_experimentset_sra_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experimentset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sraidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experimentset_id'], ['dataset_experimentset.id'], name='dataset_experimentse_experimentset_id_a234e961_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['sraidentifier_id'], ['metadata_sraidentifier.id'], name='dataset_experimentse_sraidentifier_id_0095167a_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experimentset_sra_ids_pkey'),
    sa.UniqueConstraint('experimentset_id', 'sraidentifier_id', name='dataset_experimentset_sr_experimentset_id_sraiden_9ba367aa_uniq')
    )
    op.create_index('dataset_experimentset_sra_ids_sraidentifier_id_0095167a', 'dataset_experimentset_sra_ids', ['sraidentifier_id'], unique=False)
    op.create_index('dataset_experimentset_sra_ids_experimentset_id_a234e961', 'dataset_experimentset_sra_ids', ['experimentset_id'], unique=False)
    op.create_table('metadata_refseqoffset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('"offset" >= 0', name='metadata_refseqoffset_offset_check'),
    sa.ForeignKeyConstraint(['identifier_id'], ['metadata_refseqidentifier.id'], name='metadata_refseqoffse_identifier_id_5cfb09d5_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['target_id'], ['genome_targetgene.id'], name='metadata_refseqoffse_target_id_79a5ae10_fk_genome_ta', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_refseqoffset_pkey'),
    sa.UniqueConstraint('target_id', 'identifier_id', name='metadata_refseqoffset_target_id_identifier_id_ca4d2e0b_uniq')
    )
    op.create_index('metadata_refseqoffset_target_id_79a5ae10', 'metadata_refseqoffset', ['target_id'], unique=False)
    op.create_index('metadata_refseqoffset_identifier_id_5cfb09d5', 'metadata_refseqoffset', ['identifier_id'], unique=False)
    op.create_table('main_siteinformation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('md_about', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('md_citation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('md_usage_guide', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('md_documentation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('md_terms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('md_privacy', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('version_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_siteinformation_pkey')
    )
    op.create_table('dataset_experiment_sra_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sraidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['dataset_experiment.id'], name='dataset_experiment_s_experiment_id_aa564776_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['sraidentifier_id'], ['metadata_sraidentifier.id'], name='dataset_experiment_s_sraidentifier_id_23618d15_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experiment_sra_ids_pkey'),
    sa.UniqueConstraint('experiment_id', 'sraidentifier_id', name='dataset_experiment_sra_i_experiment_id_sraidentif_3c894db8_uniq')
    )
    op.create_index('dataset_experiment_sra_ids_sraidentifier_id_23618d15', 'dataset_experiment_sra_ids', ['sraidentifier_id'], unique=False)
    op.create_index('dataset_experiment_sra_ids_experiment_id_aa564776', 'dataset_experiment_sra_ids', ['experiment_id'], unique=False)
    op.create_table('metadata_genomeidentifier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metadata_genomeidentifier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_genomeidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_genomeidentifier_identifier_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('metadata_genomeidentifier_identifier_cbbf28e9_like', 'metadata_genomeidentifier', ['identifier'], unique=False)
    op.create_table('main_licence',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('main_licence_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('long_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('legal_code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_licence_pkey'),
    sa.UniqueConstraint('short_name', name='main_licence_short_name_f9b67fee_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('main_licence_short_name_f9b67fee_like', 'main_licence', ['short_name'], unique=False)
    op.create_table('guardian_userobjectpermission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_pk', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='guardian_userobjectp_content_type_id_2e892405_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='guardian_userobjectp_permission_id_71807bfc_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='guardian_userobjectpermission_user_id_d5c1e964_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='guardian_userobjectpermission_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', 'object_pk', name='guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq')
    )
    op.create_index('guardian_userobjectpermission_user_id_d5c1e964', 'guardian_userobjectpermission', ['user_id'], unique=False)
    op.create_index('guardian_userobjectpermission_permission_id_71807bfc', 'guardian_userobjectpermission', ['permission_id'], unique=False)
    op.create_index('guardian_userobjectpermission_content_type_id_2e892405', 'guardian_userobjectpermission', ['content_type_id'], unique=False)
    op.create_table('dataset_publicdatasetcounter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('experimentsets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dataset_publicdatasetcounter_pkey')
    )
    op.create_table('social_auth_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='social_auth_code_pkey'),
    sa.UniqueConstraint('email', 'code', name='social_auth_code_email_code_801b2d02_uniq')
    )
    op.create_index('social_auth_code_timestamp_176b341f', 'social_auth_code', ['timestamp'], unique=False)
    op.create_index('social_auth_code_code_a2393167_like', 'social_auth_code', ['code'], unique=False)
    op.create_index('social_auth_code_code_a2393167', 'social_auth_code', ['code'], unique=False)
    op.create_table('genome_genomicinterval',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('end', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chromosome', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('strand', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('reference_map_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('"end" >= 0', name='genome_genomicinterval_end_check'),
    sa.CheckConstraint('start >= 0', name='genome_genomicinterval_start_check'),
    sa.ForeignKeyConstraint(['reference_map_id'], ['genome_referencemap.id'], name='genome_genomicinterv_reference_map_id_99a3ba00_fk_genome_re', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='genome_genomicinterval_pkey')
    )
    op.create_index('genome_genomicinterval_reference_map_id_99a3ba00', 'genome_genomicinterval', ['reference_map_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_group_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auth_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('dataset_experimentset_doi_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experimentset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doiidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doiidentifier_id'], ['metadata_doiidentifier.id'], name='dataset_experimentse_doiidentifier_id_5497853c_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['experimentset_id'], ['dataset_experimentset.id'], name='dataset_experimentse_experimentset_id_75a608a7_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experimentset_doi_ids_pkey'),
    sa.UniqueConstraint('experimentset_id', 'doiidentifier_id', name='dataset_experimentset_do_experimentset_id_doiiden_e76c9115_uniq')
    )
    op.create_index('dataset_experimentset_doi_ids_experimentset_id_75a608a7', 'dataset_experimentset_doi_ids', ['experimentset_id'], unique=False)
    op.create_index('dataset_experimentset_doi_ids_doiidentifier_id_5497853c', 'dataset_experimentset_doi_ids', ['doiidentifier_id'], unique=False)
    op.create_table('dataset_scoreset',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dataset_scoreset_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_child_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('abstract_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('method_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('urn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('dataset_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('normalised', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('licence_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('replaces_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_state', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('data_usage_policy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='dataset_scoreset_created_by_id_8e4fd7d0_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['dataset_experiment.id'], name='dataset_scoreset_experiment_id_f6f4acd5_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['licence_id'], ['main_licence.id'], name='dataset_scoreset_licence_id_fe8c45ec_fk_main_licence_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['modified_by_id'], ['auth_user.id'], name='dataset_scoreset_modified_by_id_d3e6e918_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['replaces_id'], ['dataset_scoreset.id'], name='dataset_scoreset_replaces_id_463b1c7b_fk_dataset_scoreset_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_pkey'),
    sa.UniqueConstraint('replaces_id', name='dataset_scoreset_replaces_id_key'),
    sa.UniqueConstraint('urn', name='dataset_scoreset_urn_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('dataset_scoreset_urn_505317a9_like', 'dataset_scoreset', ['urn'], unique=False)
    op.create_index('dataset_scoreset_modified_by_id_d3e6e918', 'dataset_scoreset', ['modified_by_id'], unique=False)
    op.create_index('dataset_scoreset_licence_id_fe8c45ec', 'dataset_scoreset', ['licence_id'], unique=False)
    op.create_index('dataset_scoreset_experiment_id_f6f4acd5', 'dataset_scoreset', ['experiment_id'], unique=False)
    op.create_index('dataset_scoreset_created_by_id_8e4fd7d0', 'dataset_scoreset', ['created_by_id'], unique=False)
    op.create_table('genome_referencegenome',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('genome_referencegenome_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('organism_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('genome_id_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genome_id_id'], ['metadata_genomeidentifier.id'], name='genome_referencegeno_genome_id_id_93c131c0_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='genome_referencegenome_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('genome_referencegenome_genome_id_id_93c131c0', 'genome_referencegenome', ['genome_id_id'], unique=False)
    op.create_table('metadata_ensembloffset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('identifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('"offset" >= 0', name='metadata_ensembloffset_offset_check'),
    sa.ForeignKeyConstraint(['identifier_id'], ['metadata_ensemblidentifier.id'], name='metadata_ensembloffs_identifier_id_33296b8d_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['target_id'], ['genome_targetgene.id'], name='metadata_ensembloffs_target_id_f79b10d6_fk_genome_ta', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_ensembloffset_pkey'),
    sa.UniqueConstraint('target_id', 'identifier_id', name='metadata_ensembloffset_target_id_identifier_id_70389f2c_uniq')
    )
    op.create_index('metadata_ensembloffset_target_id_f79b10d6', 'metadata_ensembloffset', ['target_id'], unique=False)
    op.create_index('metadata_ensembloffset_identifier_id_33296b8d', 'metadata_ensembloffset', ['identifier_id'], unique=False)
    op.create_table('guardian_groupobjectpermission',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_pk', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='guardian_groupobject_content_type_id_7ade36b8_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='guardian_groupobject_group_id_4bbbfb62_fk_auth_grou', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='guardian_groupobject_permission_id_36572738_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='guardian_groupobjectpermission_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', 'object_pk', name='guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq')
    )
    op.create_index('guardian_groupobjectpermission_permission_id_36572738', 'guardian_groupobjectpermission', ['permission_id'], unique=False)
    op.create_index('guardian_groupobjectpermission_group_id_4bbbfb62', 'guardian_groupobjectpermission', ['group_id'], unique=False)
    op.create_index('guardian_groupobjectpermission_content_type_id_7ade36b8', 'guardian_groupobjectpermission', ['content_type_id'], unique=False)
    op.create_table('reversion_revision',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reversion_revision_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='reversion_revision_user_id_17095f45_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='reversion_revision_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('reversion_revision_user_id_17095f45', 'reversion_revision', ['user_id'], unique=False)
    op.create_index('reversion_revision_date_created_96f7c20c', 'reversion_revision', ['date_created'], unique=False)
    op.create_table('main_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='main_news_pkey')
    )
    op.create_table('dataset_experiment_pubmed_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pubmedidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['dataset_experiment.id'], name='dataset_experiment_p_experiment_id_e058be6c_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['pubmedidentifier_id'], ['metadata_pubmedidentifier.id'], name='dataset_experiment_p_pubmedidentifier_id_9262b233_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experiment_pubmed_ids_pkey'),
    sa.UniqueConstraint('experiment_id', 'pubmedidentifier_id', name='dataset_experiment_pubme_experiment_id_pubmediden_12d595e4_uniq')
    )
    op.create_index('dataset_experiment_pubmed_ids_pubmedidentifier_id_9262b233', 'dataset_experiment_pubmed_ids', ['pubmedidentifier_id'], unique=False)
    op.create_index('dataset_experiment_pubmed_ids_experiment_id_e058be6c', 'dataset_experiment_pubmed_ids', ['experiment_id'], unique=False)
    op.create_table('manager_userrole',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='manager_userrole_user_id_644002f3_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='manager_userrole_pkey'),
    sa.UniqueConstraint('user_id', name='manager_userrole_user_id_key')
    )
    op.create_table('social_auth_partial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('next_step', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('backend', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('next_step >= 0', name='social_auth_partial_next_step_check'),
    sa.PrimaryKeyConstraint('id', name='social_auth_partial_pkey')
    )
    op.create_index('social_auth_partial_token_3017fea3_like', 'social_auth_partial', ['token'], unique=False)
    op.create_index('social_auth_partial_token_3017fea3', 'social_auth_partial', ['token'], unique=False)
    op.create_index('social_auth_partial_timestamp_50f2119f', 'social_auth_partial', ['timestamp'], unique=False)
    op.create_table('metadata_keyword',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='metadata_keyword_pkey'),
    sa.UniqueConstraint('text', name='metadata_keyword_text_key')
    )
    op.create_index('metadata_keyword_text_6c84ecc5_like', 'metadata_keyword', ['text'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('dataset_experimentset',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dataset_experimentset_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_child_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('abstract_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('method_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('urn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_state', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['auth_user.id'], name='dataset_experimentset_created_by_id_d91fa9d1_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['modified_by_id'], ['auth_user.id'], name='dataset_experimentset_modified_by_id_cdcd274f_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experimentset_pkey'),
    sa.UniqueConstraint('urn', name='dataset_experimentset_urn_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('dataset_experimentset_urn_f732d47b_like', 'dataset_experimentset', ['urn'], unique=False)
    op.create_index('dataset_experimentset_modified_by_id_cdcd274f', 'dataset_experimentset', ['modified_by_id'], unique=False)
    op.create_index('dataset_experimentset_created_by_id_d91fa9d1', 'dataset_experimentset', ['created_by_id'], unique=False)
    op.create_table('social_auth_usersocialauth',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('uid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='social_auth_usersocialauth_pkey'),
    sa.UniqueConstraint('provider', 'uid', name='social_auth_usersocialauth_provider_uid_e6b5e668_uniq')
    )
    op.create_index('social_auth_usersocialauth_user_id_17d28448', 'social_auth_usersocialauth', ['user_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('accounts_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('auth_token_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('submission_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='accounts_profile_user_id_49a85d32_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='accounts_profile_pkey'),
    sa.UniqueConstraint('user_id', name='accounts_profile_user_id_key')
    )
    op.create_table('variant_variant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('urn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hgvs_nt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hgvs_pro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hgvs_splice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='variant_variant_scoreset_id_1bb9e259_fk_dataset_scoreset_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='variant_variant_pkey'),
    sa.UniqueConstraint('urn', name='variant_variant_urn_key')
    )
    op.create_index('variant_variant_urn_c3db4a8b_like', 'variant_variant', ['urn'], unique=False)
    op.create_index('variant_variant_scoreset_id_1bb9e259', 'variant_variant', ['scoreset_id'], unique=False)
    op.create_table('dataset_scoreset_pubmed_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pubmedidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pubmedidentifier_id'], ['metadata_pubmedidentifier.id'], name='dataset_scoreset_pub_pubmedidentifier_id_ba5197ac_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_pub_scoreset_id_d5cccd08_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_pubmed_ids_pkey'),
    sa.UniqueConstraint('scoreset_id', 'pubmedidentifier_id', name='dataset_scoreset_pubmed__scoreset_id_pubmedidenti_c5c7db45_uniq')
    )
    op.create_index('dataset_scoreset_pubmed_ids_scoreset_id_d5cccd08', 'dataset_scoreset_pubmed_ids', ['scoreset_id'], unique=False)
    op.create_index('dataset_scoreset_pubmed_ids_pubmedidentifier_id_ba5197ac', 'dataset_scoreset_pubmed_ids', ['pubmedidentifier_id'], unique=False)
    op.create_table('tracking_pageview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('referer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('query_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('view_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['tracking_visitor.session_key'], name='tracking_pageview_visitor_id_a78682e5_fk_tracking_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='tracking_pageview_pkey')
    )
    op.create_index('tracking_pageview_visitor_id_a78682e5_like', 'tracking_pageview', ['visitor_id'], unique=False)
    op.create_index('tracking_pageview_visitor_id_a78682e5', 'tracking_pageview', ['visitor_id'], unique=False)
    op.create_table('genome_referencemap',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('genome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organism_name_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genome_id'], ['genome_referencegenome.id'], name='genome_referencemap_genome_id_6bccb458_fk_genome_re', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['target_id'], ['genome_targetgene.id'], name='genome_referencemap_target_id_5b68b9e1_fk_genome_targetgene_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='genome_referencemap_pkey')
    )
    op.create_index('genome_referencemap_target_id_5b68b9e1', 'genome_referencemap', ['target_id'], unique=False)
    op.create_index('genome_referencemap_genome_id_6bccb458', 'genome_referencemap', ['genome_id'], unique=False)
    op.create_table('metadata_ensemblidentifier',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('metadata_ensemblidentifier_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_ensemblidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_ensemblidentifier_identifier_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('metadata_ensemblidentifier_identifier_a56ead60_like', 'metadata_ensemblidentifier', ['identifier'], unique=False)
    op.create_table('genome_targetgene',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('ensembl_id_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refseq_id_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uniprot_id_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wt_sequence_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ensembl_id_id'], ['metadata_ensemblidentifier.id'], name='genome_targetgene_ensembl_id_id_cef7ac83_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['refseq_id_id'], ['metadata_refseqidentifier.id'], name='genome_targetgene_refseq_id_id_c212e2df_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='genome_targetgene_scoreset_id_e0025fd1_fk_dataset_scoreset_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['uniprot_id_id'], ['metadata_uniprotidentifier.id'], name='genome_targetgene_uniprot_id_id_1b5cab1b_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['wt_sequence_id'], ['genome_wildtypesequence.id'], name='genome_targetgene_wt_sequence_id_36c4af34_fk_genome_wi', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='genome_targetgene_pkey'),
    sa.UniqueConstraint('scoreset_id', name='genome_targetgene_scoreset_id_key'),
    sa.UniqueConstraint('wt_sequence_id', name='genome_targetgene_wt_sequence_id_key')
    )
    op.create_index('genome_targetgene_uniprot_id_id_1b5cab1b', 'genome_targetgene', ['uniprot_id_id'], unique=False)
    op.create_index('genome_targetgene_refseq_id_id_c212e2df', 'genome_targetgene', ['refseq_id_id'], unique=False)
    op.create_index('genome_targetgene_ensembl_id_id_cef7ac83', 'genome_targetgene', ['ensembl_id_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('genome_wildtypesequence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sequence_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genome_wildtypesequence_pkey')
    )
    op.create_table('tracking_visitor',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=39), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expiry_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiry_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('time_on_site', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='tracking_visitor_user_id_68f9235e_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('session_key', name='tracking_visitor_pkey')
    )
    op.create_index('tracking_visitor_user_id_68f9235e', 'tracking_visitor', ['user_id'], unique=False)
    op.create_index('tracking_visitor_session_key_8cd35282_like', 'tracking_visitor', ['session_key'], unique=False)
    op.create_table('dataset_scoreset_doi_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scoreset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doiidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doiidentifier_id'], ['metadata_doiidentifier.id'], name='dataset_scoreset_doi_doiidentifier_id_49ffeab1_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['scoreset_id'], ['dataset_scoreset.id'], name='dataset_scoreset_doi_scoreset_id_b81a5078_fk_dataset_s', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_scoreset_doi_ids_pkey'),
    sa.UniqueConstraint('scoreset_id', 'doiidentifier_id', name='dataset_scoreset_doi_ids_scoreset_id_doiidentifie_97abd28e_uniq')
    )
    op.create_index('dataset_scoreset_doi_ids_scoreset_id_b81a5078', 'dataset_scoreset_doi_ids', ['scoreset_id'], unique=False)
    op.create_index('dataset_scoreset_doi_ids_doiidentifier_id_49ffeab1', 'dataset_scoreset_doi_ids', ['doiidentifier_id'], unique=False)
    op.create_table('reversion_version',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('serialized_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('object_repr', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('db', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='reversion_version_content_type_id_7d0ff25c_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['reversion_revision.id'], name='reversion_version_revision_id_af9f6a9d_fk_reversion_revision_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='reversion_version_pkey'),
    sa.UniqueConstraint('db', 'content_type_id', 'object_id', 'revision_id', name='reversion_version_db_content_type_id_objec_b2c54f65_uniq')
    )
    op.create_index('reversion_version_revision_id_af9f6a9d', 'reversion_version', ['revision_id'], unique=False)
    op.create_index('reversion_version_content_type_id_7d0ff25c', 'reversion_version', ['content_type_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('dataset_experimentset_pubmed_ids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experimentset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pubmedidentifier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experimentset_id'], ['dataset_experimentset.id'], name='dataset_experimentse_experimentset_id_8b042599_fk_dataset_e', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['pubmedidentifier_id'], ['metadata_pubmedidentifier.id'], name='dataset_experimentse_pubmedidentifier_id_b112c80c_fk_metadata_', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='dataset_experimentset_pubmed_ids_pkey'),
    sa.UniqueConstraint('experimentset_id', 'pubmedidentifier_id', name='dataset_experimentset_pu_experimentset_id_pubmedi_1142d614_uniq')
    )
    op.create_index('dataset_experimentset_pubmed_ids_pubmedidentifier_id_b112c80c', 'dataset_experimentset_pubmed_ids', ['pubmedidentifier_id'], unique=False)
    op.create_index('dataset_experimentset_pubmed_ids_experimentset_id_8b042599', 'dataset_experimentset_pubmed_ids', ['experimentset_id'], unique=False)
    op.create_table('metadata_uniprotidentifier',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('identifier', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbname', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('dbversion', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_uniprotidentifier_pkey'),
    sa.UniqueConstraint('identifier', name='metadata_uniprotidentifier_identifier_key')
    )
    op.create_index('metadata_uniprotidentifier_identifier_14028ac2_like', 'metadata_uniprotidentifier', ['identifier'], unique=False)
    # ### end Alembic commands ###
