"""Roles as Enums, Access Keys can have Roles

Revision ID: 377bb8c30bde
Revises: b3767156e04a
Create Date: 2024-04-18 09:19:04.008237

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "377bb8c30bde"
down_revision = "b3767156e04a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("access_keys", sa.Column("role_id", sa.Integer(), nullable=True))
    op.create_foreign_key("access_key_roles_fk_constraint", "access_keys", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("access_key_roles_fk_constraint", "access_keys", type_="foreignkey")
    op.drop_column("access_keys", "role_id")
    # ### end Alembic commands ###
