"""Make Index on Users Unique

Revision ID: 44a45d616036
Revises: ec5d2787bec9
Create Date: 2024-08-16 13:25:14.980820

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "44a45d616036"
down_revision = "ec5d2787bec9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    # ### end Alembic commands ###
