"""simplify published variants mv indexes

Revision ID: 4726e4dddde8
Revises: b85bc7b1bec7
Create Date: 2025-03-25 10:46:46.641777

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "4726e4dddde8"
down_revision = "b85bc7b1bec7"
branch_labels = None
depends_on = None

# Frozen literal, not imported from the model: this migration replaces the historical
# mapped_variants-based MV indexes at its point in history. A later migration rebuilds the MV onto
# the mapping_records substrate and re-indexes it, so the column names below stay the legacy ones.
signature = "published_variants_materialized_view"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(f"idx_{signature}_variant_id", signature)
    op.drop_index(f"idx_{signature}_variant_urn", signature)
    op.drop_index(f"idx_{signature}_mapped_variant_id", signature)
    op.drop_index(f"idx_{signature}_score_set_id", signature)
    op.drop_index(f"idx_{signature}_score_set_urn", signature)

    op.create_index(
        f"idx_{signature}_ids",
        signature,
        ["mapped_variant_id", "variant_id", "score_set_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(f"idx_{signature}_ids", signature)

    op.create_index(
        f"idx_{signature}_variant_id",
        signature,
        ["variant_id"],
        unique=False,
    )
    op.create_index(
        f"idx_{signature}_variant_urn",
        signature,
        ["variant_urn"],
        unique=False,
    )
    op.create_index(
        f"idx_{signature}_score_set_id",
        signature,
        ["score_set_id"],
        unique=False,
    )
    op.create_index(
        f"idx_{signature}_score_set_urn",
        signature,
        ["score_set_urn"],
        unique=False,
    )
    op.create_index(
        f"idx_{signature}_mapped_variant_id",
        signature,
        ["mapped_variant_id"],
        unique=True,
    )
    # ### end Alembic commands ###
