"""controlled_keywords

Revision ID: 47338d1d0532
Revises: b3767156e04a
Create Date: 2024-04-19 16:41:04.081723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47338d1d0532'
down_revision = 'b3767156e04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('vocabulary', sa.String(), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'value', name='ix_controlled_keywords_key_value')
    )
    op.create_index(op.f('ix_controlled_keywords_id'), 'controlled_keywords', ['id'], unique=False)
    op.create_table('experiment_controlled_keywords',
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('controlled_keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controlled_keyword_id'], ['controlled_keywords.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'controlled_keyword_id')
    )

    # Insert statements.
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'SpCas9', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The system used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'SaCas9', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The system used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'AsCas12a', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The system used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'RfsCas13d', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The system used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'Nuclease', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The functional mechanism of the library generation method.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'Base editor', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The functional mechanism of the library generation method.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'Prime editor', NULL, False, 'A methodology for generating a variant library at an endogenous locus. The functional mechanism of the library generation method.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method', 'Other', NULL, False, 'A methodology for generating a variant library at an endogenous locus.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Oligo-directed mutagenic PCR', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Error-prone PCR', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Nicking mutagenesis', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Microarray synthesis', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Site-directed mutagenesis', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Doped oligo synthesis', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Oligo pool synthesis', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Proprietary method', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The type of method used to generate the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Other', NULL, False, 'A methodology for generating and integrating an exogenous variant library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Native locus replacement', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Extra-local construct insertion', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Random locus viral integration', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Episomal delivery', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Plasmid (not integrated)', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method', 'Transfection of RNA', NULL, False, 'A methodology for generating and integrating an exogenous variant library. The mechanism for integration or expression of an exogenous construct.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Electroporation', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Nucleofection', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Chemical-based transfection', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Adeno-associated virus transduction', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Lentivirus transduction', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Chemical or heat shock transformation', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Intronic', NULL, False, 'A collection of sequences that are derived from a common target sequence. The scope type for elements introduced into the library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library', 'Other', NULL, False, 'A collection of sequences that are derived from a common target sequence. How the variant library was delivered to the model system for phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Single-dimensional data', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A  coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'High-dimensional data', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Combined functional data', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Biological', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the kind of replication performed.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Technical', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the kind of replication performed.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Biological and technical', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the kind of replication performed.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'No replication', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. A coding defining the kind of replication performed.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Promoter activity reporter gene assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Bulk RNA-sequencing', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Single-cell RNA sequencing assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Fluorescence in-situ hybridization (FISH) assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Flow cytometry assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Imaging mass cytometry assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Systematic evolution of ligands by exponential enrichment assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Single cell imaging', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Multiplexed fluorescent antibody imaging', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Binding assays', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Cell proliferation assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Survival assessment assay', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Immortalized human cells', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Murine primary cells', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Induced pluripotent stem cells from human male', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Induced pluripotent stem cells from human female', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Patient derived primary cells (e.g. T-cells, adipocytes)', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Yeast', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Bacteria', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Bacteriophage', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Molecular display', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Direct sequencing', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The strategy used to profile the variant library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Shotgun sequencing', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The strategy used to profile the variant library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Barcode sequencing', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The strategy used to profile the variant library.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Single-segment (short read)', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The sequencing method used.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Single-segment (long read)', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The sequencing method used.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Multi-segment', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants. The sequencing method used.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay', 'Other', NULL, False, 'A physical adjudication of a model system that allows for systematic interrogation of a functional read-out for a large amount of genetic variants.', NOW(), NOW())""")

    # op.drop_index('ix_mapped_variants_js', table_name='mapped_variants')
    # op.drop_index('ix_variants_js', table_name='variants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_variants_js', 'variants', ['scoreset_id'], unique=False)
    # op.create_index('ix_mapped_variants_js', 'mapped_variants', ['variant_id'], unique=False)
    op.drop_table('experiment_controlled_keywords')
    op.drop_index(op.f('ix_controlled_keywords_id'), table_name='controlled_keywords')
    op.drop_table('controlled_keywords')
    # ### end Alembic commands ###
