"""add uniprot id field for mapped metadata

Revision ID: 4b9fb51a460d
Revises: aa3933cf0cb3
Create Date: 2025-07-24 16:07:51.548202

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b9fb51a460d"
down_revision = "aa3933cf0cb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("target_genes", sa.Column("uniprot_id_from_mapped_metadata", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_genes", "uniprot_id_from_mapped_metadata")
    # ### end Alembic commands ###
