"""add unique constraint on replaces_id

Revision ID: 4dbf24ed1857
Revises: 398067c53257
Create Date: 2026-05-13 11:22:59.646605

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '4dbf24ed1857'
down_revision = '398067c53257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scoresets_replaces_id', table_name='scoresets')
    op.create_index(op.f('ix_scoresets_replaces_id'), 'scoresets', ['replaces_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoresets_replaces_id'), table_name='scoresets')
    op.create_index('ix_scoresets_replaces_id', 'scoresets', ['replaces_id'], unique=False)
    # ### end Alembic commands ###
