"""Add active column to licenses

Revision ID: 68a0ec57694e
Revises: 03c7124c33e1
Create Date: 2024-10-22 15:36:41.868909

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68a0ec57694e"
down_revision = "03c7124c33e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("licenses", sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("licenses", "active")
    # ### end Alembic commands ###
