"""Add missing indices

Revision ID: 6c16989489bd
Revises: fecb3e0d181d
Create Date: 2024-03-18 18:02:14.609175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c16989489bd'
down_revision = 'fecb3e0d181d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_keys_user_id'), 'access_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_experiment_sets_created_by_id'), 'experiment_sets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_experiments_created_by_id'), 'experiments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_experiments_experiment_set_id'), 'experiments', ['experiment_set_id'], unique=False)
    op.create_index(op.f('ix_mapped_variants_variant_id'), 'mapped_variants', ['variant_id'], unique=False)
    op.create_index(op.f('ix_reference_genomes_genome_identifier_id'), 'reference_genomes', ['genome_identifier_id'], unique=False)
    op.create_index(op.f('ix_scoresets_created_by_id'), 'scoresets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_scoresets_experiment_id'), 'scoresets', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_scoresets_replaces_id'), 'scoresets', ['replaces_id'], unique=False)
    op.create_index(op.f('ix_target_genes_accession_id'), 'target_genes', ['accession_id'], unique=False)
    op.create_index(op.f('ix_target_genes_scoreset_id'), 'target_genes', ['scoreset_id'], unique=False)
    op.create_index(op.f('ix_target_genes_target_sequence_id'), 'target_genes', ['target_sequence_id'], unique=False)
    op.create_index(op.f('ix_target_sequences_reference_id'), 'target_sequences', ['reference_id'], unique=False)
    op.create_index(op.f('ix_variants_scoreset_id'), 'variants', ['scoreset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_scoreset_id'), table_name='variants')
    op.drop_index(op.f('ix_target_sequences_reference_id'), table_name='target_sequences')
    op.drop_index(op.f('ix_target_genes_target_sequence_id'), table_name='target_genes')
    op.drop_index(op.f('ix_target_genes_scoreset_id'), table_name='target_genes')
    op.drop_index(op.f('ix_target_genes_accession_id'), table_name='target_genes')
    op.drop_index(op.f('ix_scoresets_replaces_id'), table_name='scoresets')
    op.drop_index(op.f('ix_scoresets_experiment_id'), table_name='scoresets')
    op.drop_index(op.f('ix_scoresets_created_by_id'), table_name='scoresets')
    op.drop_index(op.f('ix_reference_genomes_genome_identifier_id'), table_name='reference_genomes')
    op.drop_index(op.f('ix_mapped_variants_variant_id'), table_name='mapped_variants')
    op.drop_index(op.f('ix_experiments_experiment_set_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_by_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiment_sets_created_by_id'), table_name='experiment_sets')
    op.drop_index(op.f('ix_access_keys_user_id'), table_name='access_keys')
    # ### end Alembic commands ###
