"""add gnomad variants table

Revision ID: 79b28316dd0c
Revises: 4b9fb51a460d
Create Date: 2025-06-17 08:38:51.954238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79b28316dd0c"
down_revision = "4b9fb51a460d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gnomad_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("db_name", sa.String(), nullable=False),
        sa.Column("db_identifier", sa.String(), nullable=False),
        sa.Column("db_version", sa.String(), nullable=False),
        sa.Column("allele_count", sa.Integer(), nullable=False),
        sa.Column("allele_number", sa.Integer(), nullable=False),
        sa.Column("allele_frequency", sa.Float(), nullable=False),
        sa.Column("faf95_max", sa.Float(), nullable=False),
        sa.Column("faf95_max_ancestry", sa.String(), nullable=False),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("modification_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gnomad_variants_db_identifier"), "gnomad_variants", ["db_identifier"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gnomad_variants_db_identifier"), table_name="gnomad_variants")
    op.drop_table("gnomad_variants")
    # ### end Alembic commands ###
