"""Unify publication identifier date fields

Revision ID: 7a345f1bf9c3
Revises: 2c8d7e2bf2fe
Create Date: 2024-05-17 16:09:39.508434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a345f1bf9c3"
down_revision = "2c8d7e2bf2fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE publication_identifiers SET publication_year = date_part('year', preprint_date) WHERE publication_journal = 'Preprint';"
    )
    op.drop_column("publication_identifiers", "preprint_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publication_identifiers", sa.Column("preprint_date", sa.DATE(), autoincrement=False, nullable=True))
    # TODO: There isn't a great way to re-populate this column.

    # ### end Alembic commands ###
