"""taxonomy

Revision ID: 7c37c18e3246
Revises: 33e99d4b90cc
Create Date: 2023-06-09 14:38:20.089290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c37c18e3246'
down_revision = '33e99d4b90cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('organism_names', sa.String(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('genome_identifier_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['genome_identifier_id'], ['genome_identifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomies_id'), 'taxonomies', ['id'], unique=False)

    op.add_column('target_genes', sa.Column('taxonomy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'target_genes', 'taxonomies', ['taxonomy_id'], ['id'])

    op.execute("""INSERT INTO taxonomies VALUES (1, 212017, 'Lethocerus indicus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (2, 31604, 'Small ruminant morbillivirus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (3, 3702, 'Arabidopsis thaliana', 'thale cress', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (4, 559292, 'Saccharomyces cerevisiae S288C', NULL, 6, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (5, 254252, 'Lactococcus virus P2', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (6, 1521, 'Ruminiclostridium cellulolyticum', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (7, 9913, 'Bos taurus', 'cattle', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (8, 9823, 'Sus scrofa', 'pig', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (9, 223997, 'Murine norovirus 1', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (10, 70601, 'Pyrococcus horikoshii OT3', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (11, 10710, 'Lambdavirus lambda', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (12, 10754, 'Lederbergvirus P22', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (13, 271848, 'Burkholderia thailandensis E264', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (14, 9606, 'Homo sapiens', 'human', 5, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (15, 392021, 'Rickettsia rickettsii str. ''Sheila Smith''', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (16, 294381, 'Entamoeba histolytica HM-1:IMSS', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (17, 90371, 'Salmonella enterica subsp. enterica serovar Typhimurium', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (18, 211044, 'Influenza A virus (A/Puerto Rico/8/1934(H1N1))', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (19, 83332, 'Mycobacterium tuberculosis H37Rv', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (20, 226185, 'Enterococcus faecalis V583', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (21, 3055, 'Chlamydomonas reinhardtii', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (22, 7227, 'Drosophila melanogaster', 'fruit fly', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (23, 196620, 'Staphylococcus aureus subsp. aureus MW2', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (24, 103690, 'Nostoc sp. PCC 7120 = FACHB-418', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (25, 85962, 'Helicobacter pylori 26695', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (26, 224308, 'Bacillus subtilis subsp. subtilis str. 168', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (27, 262724, 'Thermus thermophilus HB27', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (28, 1280, 'Staphylococcus aureus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (29, 31634, 'Dengue virus 2 Thailand/16681/84', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (30, 4784, 'Phytophthora capsici', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (31, 195102, 'Clostridium perfringens str. 13', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (32, 1260, 'Finegoldia magna', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (33, 170187, 'Streptococcus pneumoniae TIGR4', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (34, 8201, 'Lycodichthys dearborni', 'Antarctic eel pout', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (35, 83333, 'Escherichia coli K-12', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (36, 94237, 'Mola mola', 'ocean sunfish', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (37, 1351, 'Enterococcus faecalis', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (38, 224324, 'Aquifex aeolicus VF5', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (39, 272560, 'Burkholderia pseudomallei K96243', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (40, 1422, 'Geobacillus stearothermophilus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (41, 203119, 'Acetivibrio thermocellus ATCC 27405', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (42, 258594, 'Rhodopseudomonas palustris CGA009', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (43, 269799, 'Geobacter metallireducens GS-15', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (44, 287, 'Pseudomonas aeruginosa', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (45, 32049, 'Synechococcus sp. PCC 7002', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (46, 64320, 'Zika virus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (47, 274, 'Thermus thermophilus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (48, 187420, 'Methanothermobacter thermautotrophicus str. Delta H', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (49, 1961, 'Streptomyces virginiae', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (50, 48416, 'Zoarces viviparus', 'viviparous blenny', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (51, 316385, 'Escherichia coli str. K-12 substr. DH10B', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (52, 387139, 'Influenza A virus (A/Aichi/2/1968(H3N2))', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (53, 351614, 'Xenorhabdus stockiae', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (54, 93061, 'Staphylococcus aureus subsp. aureus NCTC 8325', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (55, 232237, 'Xipdecavirus Xp10', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (56, 272620, 'Klebsiella pneumoniae subsp. pneumoniae MGH 78578', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (57, 562, 'Escherichia coli', 'E. coli', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (58, 9031, 'Gallus gallus', 'chicken', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (59, 282458, 'Staphylococcus aureus subsp. aureus MRSA252', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (60, 169963, 'Listeria monocytogenes EGD-e', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (61, 469008, 'Escherichia coli BL21(DE3)', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (62, 114727, 'H1N1 subtype', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (63, 463722, 'Murine norovirus GV/CR6/2005/USA', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (64, 211586, 'Shewanella oneidensis MR-1', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (65, 8199, 'Zoarces americanus', 'ocean pout', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (66, 218491, 'Pectobacterium atrosepticum SCRI1043', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (67, 484895, 'Bruynoghevirus LUZ24', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (68, 44689, 'Dictyostelium discoideum', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (69, 10116, 'Rattus norvegicus', 'Norway rat', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (70, 194439, 'Chlorobaculum tepidum TLS', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (71, 10760, 'Escherichia phage T7', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (72, 523795, 'Porcine enteric sapovirus swine/Cowden/1980/US', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (73, 6239, 'Caenorhabditis elegans', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (74, 6100, 'Aequorea victoria', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (75, 33113, 'Atropa belladonna', 'belladonna', NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (76, 29413, 'Nostoc sp. PCC 8009', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (77, 243232, 'Methanocaldococcus jannaschii DSM 2661', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (78, 1320, 'Streptococcus sp. ''group G''', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (79, 273057, 'Saccharolobus solfataricus P2', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (80, 34, 'Myxococcus xanthus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (81, 99287, 'Salmonella enterica subsp. enterica serovar Typhimurium str. LT2', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (82, 291231, 'Zoarces elongatus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (83, 2681611, 'Escherichia phage Lambda', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (84, 1314, 'Streptococcus pyogenes', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (85, 246200, 'Ruegeria pomeroyi DSS-3', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (86, 195103, 'Clostridium perfringens ATCC 13124', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (87, 1185654, 'Pyrococcus furiosus COM1', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (88, 1515, 'Acetivibrio thermocellus', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (89, 2697049, 'Severe acute respiratory syndrome coronavirus 2', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (90, 10090, 'Mus musculus', 'house mouse', 8, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (91, 1111708, 'Synechocystis sp. PCC 6803 substr. Kazusa', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (92, 10712, 'Phage 434', NULL, NULL, NOW(), NOW())""")
    op.execute("""INSERT INTO taxonomies VALUES (93, 37553, 'Saprolegnia monoica', NULL, NULL, NOW(), NOW())""")

    """
    This part doesn't work correctly. All of taxonomy_id are updated to 90.
    #Homo sapiens
    op.execute(
        
        UPDATE target_genes
        SET taxonomy_id = 14
        FROM reference_maps, reference_genomes  
        WHERE reference_maps.genome_id = reference_genomes.id
        AND reference_maps.genome_id IN (1,2,3,4,5) 
        
    )

    #Saccharomyces cerevisiae
    op.execute(
        
        UPDATE target_genes
        SET taxonomy_id = 4
        FROM reference_maps, reference_genomes
        WHERE reference_maps.genome_id = reference_genomes.id
        AND reference_maps.genome_id = 7
        
    )
    #Mus musculus
    op.execute(
        
        UPDATE target_genes
        SET taxonomy_id = 90
        FROM reference_maps, reference_genomes  
        WHERE reference_maps.genome_id = reference_genomes.id
        AND reference_maps.genome_id IN (9, 10)
        
    )
    """
    op.drop_index('ix_reference_maps_id', table_name='reference_maps')
    op.drop_table('reference_maps')
    op.drop_index('ix_reference_genomes_id', table_name='reference_genomes')
    op.drop_table('reference_genomes')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target_genes', type_='foreignkey')
    op.drop_column('target_genes', 'taxonomy_id')

    op.create_table('reference_maps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('genome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['reference_genomes.id'], name='reference_maps_genome_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['target_genes.id'], name='reference_maps_target_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reference_maps_pkey')
    )
    op.create_index('ix_reference_maps_id', 'reference_maps', ['id'], unique=False)
    op.create_table('reference_genomes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organism_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genome_identifier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('modification_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genome_identifier_id'], ['genome_identifiers.id'], name='reference_genomes_genome_identifier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reference_genomes_pkey')
    )
    op.create_index('ix_reference_genomes_id', 'reference_genomes', ['id'], unique=False)

    op.drop_index(op.f('ix_taxonomies_id'), table_name='taxonomies')
    op.drop_table('taxonomies')
    # ### end Alembic commands ###
