"""score set processing errors

Revision ID: 886e059ad1a8
Revises: fecb3e0d181d
Create Date: 2024-03-19 16:28:05.797406

"""

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision = "886e059ad1a8"
down_revision = "fecb3e0d181d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scoresets", sa.Column("processing_errors", JSONB, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoresets", "processing_errors")
    # ### end Alembic commands ###
