"""add pipeline and job tracking tables

Revision ID: 8de33cc35cd7
Revises: dcf8572d3a17
Create Date: 2026-01-28 10:08:36.906494

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8de33cc35cd7"
down_revision = "dcf8572d3a17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipelines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("urn", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Flexible metadata storage for pipeline-specific data",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("mavedb_version", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'running', 'succeeded', 'failed', 'cancelled', 'paused', 'partial')",
            name="ck_pipelines_status_valid",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("urn"),
    )
    op.create_index("ix_pipelines_correlation_id", "pipelines", ["correlation_id"], unique=False)
    op.create_index("ix_pipelines_created_at", "pipelines", ["created_at"], unique=False)
    op.create_index("ix_pipelines_created_by_user_id", "pipelines", ["created_by_user_id"], unique=False)
    op.create_index("ix_pipelines_status", "pipelines", ["status"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("urn", sa.String(length=255), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("job_function", sa.String(length=255), nullable=False),
        sa.Column("job_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("retry_delay_seconds", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column("failure_category", sa.String(length=100), nullable=True),
        sa.Column("progress_current", sa.Integer(), nullable=True),
        sa.Column("progress_total", sa.Integer(), nullable=True),
        sa.Column("progress_message", sa.String(length=500), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("mavedb_version", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', 'skipped')",
            name="ck_job_runs_status_valid",
        ),
        sa.CheckConstraint("max_retries >= 0", name="ck_job_runs_max_retries_positive"),
        sa.CheckConstraint("priority >= 0", name="ck_job_runs_priority_positive"),
        sa.CheckConstraint("retry_count >= 0", name="ck_job_runs_retry_count_positive"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("urn"),
    )
    op.create_index("ix_job_runs_correlation_id", "job_runs", ["correlation_id"], unique=False)
    op.create_index("ix_job_runs_created_at", "job_runs", ["created_at"], unique=False)
    op.create_index("ix_job_runs_job_type", "job_runs", ["job_type"], unique=False)
    op.create_index("ix_job_runs_pipeline_id", "job_runs", ["pipeline_id"], unique=False)
    op.create_index("ix_job_runs_scheduled_at", "job_runs", ["scheduled_at"], unique=False)
    op.create_index("ix_job_runs_status", "job_runs", ["status"], unique=False)
    op.create_index("ix_job_runs_status_scheduled", "job_runs", ["status", "scheduled_at"], unique=False)
    op.create_table(
        "job_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("depends_on_job_id", sa.Integer(), nullable=False),
        sa.Column("dependency_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "dependency_type IS NULL OR dependency_type IN ('success_required', 'completion_required')",
            name="ck_job_dependencies_type_valid",
        ),
        sa.ForeignKeyConstraint(["depends_on_job_id"], ["job_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id"], ["job_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "depends_on_job_id"),
    )
    op.create_index("ix_job_dependencies_created_at", "job_dependencies", ["created_at"], unique=False)
    op.create_index("ix_job_dependencies_depends_on_job_id", "job_dependencies", ["depends_on_job_id"], unique=False)
    op.create_table(
        "variant_annotation_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column(
            "annotation_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of annotation: vrs, clinvar, gnomad, etc.",
        ),
        sa.Column(
            "version",
            sa.String(length=50),
            nullable=True,
            comment="Version of the annotation source used (if applicable)",
        ),
        sa.Column("status", sa.String(length=50), nullable=False, comment="success, failed, skipped, pending"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("failure_category", sa.String(length=100), nullable=True),
        sa.Column(
            "success_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Annotation results when successful",
        ),
        sa.Column(
            "current",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether this is the current status for the variant and annotation type",
        ),
        sa.Column("job_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "annotation_type IN ('vrs_mapping', 'clingen_allele_id', 'mapped_hgvs', 'variant_translation', 'gnomad_allele_frequency', 'clinvar_control', 'vep_functional_consequence', 'ldh_submission')",
            name="ck_variant_annotation_type_valid",
        ),
        sa.CheckConstraint("status IN ('success', 'failed', 'skipped')", name="ck_variant_annotation_status_valid"),
        sa.ForeignKeyConstraint(["job_run_id"], ["job_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["variant_id"], ["variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_variant_annotation_status_annotation_type", "variant_annotation_status", ["annotation_type"], unique=False
    )
    op.create_index(
        "ix_variant_annotation_status_created_at", "variant_annotation_status", ["created_at"], unique=False
    )
    op.create_index("ix_variant_annotation_status_current", "variant_annotation_status", ["current"], unique=False)
    op.create_index(
        "ix_variant_annotation_status_job_run_id", "variant_annotation_status", ["job_run_id"], unique=False
    )
    op.create_index("ix_variant_annotation_status_status", "variant_annotation_status", ["status"], unique=False)
    op.create_index(
        "ix_variant_annotation_status_variant_id", "variant_annotation_status", ["variant_id"], unique=False
    )
    op.create_index(
        "ix_variant_annotation_status_variant_type_version_current",
        "variant_annotation_status",
        ["variant_id", "annotation_type", "version", "current"],
        unique=False,
    )
    op.create_index("ix_variant_annotation_status_version", "variant_annotation_status", ["version"], unique=False)
    op.create_index(
        "ix_variant_annotation_type_status", "variant_annotation_status", ["annotation_type", "status"], unique=False
    )
    op.create_index(
        "ix_variant_annotation_variant_type_status",
        "variant_annotation_status",
        ["variant_id", "annotation_type", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_variant_annotation_variant_type_status", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_type_status", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_version", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_variant_type_version_current", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_variant_id", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_status", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_job_run_id", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_current", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_created_at", table_name="variant_annotation_status")
    op.drop_index("ix_variant_annotation_status_annotation_type", table_name="variant_annotation_status")
    op.drop_table("variant_annotation_status")
    op.drop_index("ix_job_dependencies_depends_on_job_id", table_name="job_dependencies")
    op.drop_index("ix_job_dependencies_created_at", table_name="job_dependencies")
    op.drop_table("job_dependencies")
    op.drop_index("ix_job_runs_status_scheduled", table_name="job_runs")
    op.drop_index("ix_job_runs_status", table_name="job_runs")
    op.drop_index("ix_job_runs_scheduled_at", table_name="job_runs")
    op.drop_index("ix_job_runs_pipeline_id", table_name="job_runs")
    op.drop_index("ix_job_runs_job_type", table_name="job_runs")
    op.drop_index("ix_job_runs_created_at", table_name="job_runs")
    op.drop_index("ix_job_runs_correlation_id", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index("ix_pipelines_status", table_name="pipelines")
    op.drop_index("ix_pipelines_created_by_user_id", table_name="pipelines")
    op.drop_index("ix_pipelines_created_at", table_name="pipelines")
    op.drop_index("ix_pipelines_correlation_id", table_name="pipelines")
    op.drop_table("pipelines")
    # ### end Alembic commands ###
