"""controlled_keyword

Revision ID: 9702d32bacb3
Revises: 7a345f1bf9c3
Create Date: 2024-05-24 14:48:50.266496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9702d32bacb3'
down_revision = 'ec5d2787bec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('vocabulary', sa.String(), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'value', name='ix_controlled_keywords_key_value')
    )
    op.create_index(op.f('ix_controlled_keywords_id'), 'controlled_keywords', ['id'], unique=False)
    op.create_table('experiment_controlled_keywords',
                    sa.Column('experiment_id', sa.Integer(), nullable=False),
                    sa.Column('controlled_keyword_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['controlled_keyword_id'], ['controlled_keywords.id'], ),
                    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
                    sa.PrimaryKeyConstraint('experiment_id', 'controlled_keyword_id'))

    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library Creation Method', 'Endogenous locus library method', NULL, False, 'A methodology for generating a variant library at an endogenous locus', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library Creation Method', 'In vitro construct library method', NULL, False, 'A methodology for generating a variant library at an endogenous locus', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Variant Library Creation Method', 'Other', NULL, False, 'A methodology for generating a variant library at an endogenous locus', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method System', 'SpCas9', NULL, False, 'The system used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method System', 'SaCas9', NULL, False, 'The system used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method System', 'AsCas12a', NULL, False, 'The system used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method System', 'RfsCas13d', NULL, False, 'The system used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method System', 'Other', NULL, False, 'The system used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method Mechanism', 'Nuclease', NULL, False, 'The functional mechanism of the library generation method', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method Mechanism', 'Base editor', NULL, False, 'The functional mechanism of the library generation method', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method Mechanism', 'Prime editor', NULL, False, 'The functional mechanism of the library generation method', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Endogenous Locus Library Method Mechanism', 'Other', NULL, False, 'The functional mechanism of the library generation method', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Oligo-directed mutagenic PCR', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Error-prone PCR', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Nicking mutagenesis', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Microarray synthesis', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Site-directed mutagenesis', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Doped oligo synthesis', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Oligo pool synthesis', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Proprietary method', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method System', 'Other', NULL, False, 'The type of method used to generate the library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Native locus replacement', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Extra-local construct insertion', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Random locus viral integration', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Episomal delivery', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Plasmid (not integrated)', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Transfection of RNA', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('In Vitro Construct Library Method Mechanism', 'Other', NULL, False, 'The mechanism for integration or expression of an exogenous construct', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Electroporation', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Nucleofection', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Chemical-based transfection', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Adeno-associated virus transduction', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Tentivirus transduction', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Chemical or heat shock transformation', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Delivery method', 'Other', NULL, False, 'How the variant library was delivered to the model system for phenotype evaluation.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Dimensionality', 'Single-dimensional data', NULL, False, 'A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Dimensionality', 'High-dimensional data', NULL, False, 'A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Dimensionality', 'Combined functional data', NULL, False, 'A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Dimensionality', 'Other', NULL, False, 'A coding defining the dimensionality of the assay as single or multiple functional readouts.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Promoter activity detection by reporter gene assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Bulk RNA-sequencing', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Single-cell RNA sequencing assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Fluorescence in-situ hybridization (FISH) assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Flow cytometry assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Imaging mass cytometry assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Systematic evolution of ligands by exponential enrichment assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Single cell imaging', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Multiplexed fluorescent antibody imaging', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Binding assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Cell proliferation assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Survival assessment assay', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Method', 'Other', NULL, False, 'The assay method, defining the molecular properties interrogated.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Immortalized human cells', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Murine primary cells', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Induced pluripotent stem cells from human male', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Induced pluripotent stem cells from human female', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Patient derived primary cells (e.g. T-cells, adipocytes)', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Yeast', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Bacteria', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Bacteriophage', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Molecular display', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Model System', 'Other', NULL, False, 'The model system context that influences expression of the phenotype.', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Profiling Strategy', 'Direct sequencing', NULL, False, 'The strategy used to profile the variant library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Profiling Strategy', 'Shotgun sequencing', NULL, False, 'The strategy used to profile the variant library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Profiling Strategy', 'Barcode sequencing', NULL, False, 'The strategy used to profile the variant library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Profiling Strategy', 'Other', NULL, False, 'The strategy used to profile the variant library', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Sequencing Read Type', 'Single-segment (short read)', NULL, False, 'The sequencing method used', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Sequencing Read Type', 'Single-segment (long read)', NULL, False, 'The sequencing method used', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Sequencing Read Type', 'Multi-segment', NULL, False, 'The sequencing method used', NOW(), NOW())""")
    op.execute(
        """INSERT INTO controlled_keywords (key, value, vocabulary, special, description, creation_date, modification_date) VALUES ('Phenotypic Assay Sequencing Read Type', 'Other', NULL, False, 'The sequencing method used', NOW(), NOW())""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_controlled_keywords')
    op.drop_index(op.f('ix_controlled_keywords_id'), table_name='controlled_keywords')
    op.drop_table('controlled_keywords')
    # ### end Alembic commands ###
