"""Variant translations data model

Revision ID: 986b635a697f
Revises: af87c9953d2d
Create Date: 2025-03-24 14:00:18.063245

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "986b635a697f"
down_revision = "af87c9953d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variant_translations",
        sa.Column("aa_clingen_id", sa.String(), nullable=False),
        sa.Column("nt_clingen_id", sa.String(), nullable=False),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("modification_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("aa_clingen_id", "nt_clingen_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variant_translations")
    # ### end Alembic commands ###
