"""Add progress_updated_at heartbeat column to job_runs

Revision ID: a7f3c2e9b104
Revises: 4dbf24ed1857
Create Date: 2026-07-09 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7f3c2e9b104"
down_revision = "4dbf24ed1857"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_runs",
        sa.Column(
            "progress_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_job_runs_status_progress_updated",
        "job_runs",
        ["status", "progress_updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_runs_status_progress_updated", table_name="job_runs")
    op.drop_column("job_runs", "progress_updated_at")
    # ### end Alembic commands ###
