"""cast db_identifier in clinical controls table to a string

Revision ID: a8e345cca190
Revises: 986b635a697f
Create Date: 2025-08-20 12:30:05.388503

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8e345cca190"
down_revision = "986b635a697f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clinical_controls", "db_identifier", existing_type=sa.INTEGER(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "publication_identifiers", "title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "publication_identifiers", "abstract", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "publication_identifiers",
        "publication_journal",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "publication_identifiers",
        "publication_journal",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "publication_identifiers", "abstract", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "publication_identifiers", "title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "clinical_controls", "db_identifier", existing_type=sa.String(), type_=sa.INTEGER(), existing_nullable=False
    )
    # ### end Alembic commands ###
