"""score set level score thresholds

Revision ID: aa73d39b3705
Revises: 03c7124c33e1
Create Date: 2024-11-13 11:23:57.917725

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aa73d39b3705"
down_revision = "03c7124c33e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scoresets", sa.Column("score_calibrations", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoresets", "score_calibrations")
    # ### end Alembic commands ###
