"""add_calibration_superseded_column

Revision ID: adb481b7c60b
Revises: 398067c53257
Create Date: 2026-06-01 16:45:35.507837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adb481b7c60b'
down_revision = '398067c53257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_calibrations', sa.Column('replaces_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_score_calibrations_replaces_id'), 'score_calibrations', ['replaces_id'], unique=False)
    op.create_foreign_key(None, 'score_calibrations', 'score_calibrations', ['replaces_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_calibrations', type_='foreignkey')
    op.drop_index(op.f('ix_score_calibrations_replaces_id'), table_name='score_calibrations')
    op.drop_column('score_calibrations', 'replaces_id')
    # ### end Alembic commands ###
