"""consolidate score ranges and calibrations

Revision ID: af87c9953d2d
Revises: ec535fd72270
Create Date: 2025-07-09 21:04:33.916597

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "af87c9953d2d"
down_revision = "ec535fd72270"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoresets", "score_calibrations")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoresets",
        sa.Column("score_calibrations", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
