"""Add mapped hgvs

Revision ID: b22b450d409c
Revises: 1e08b947679d
Create Date: 2025-10-09 09:53:47.903249

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b22b450d409c"
down_revision = "1e08b947679d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mapped_variants", sa.Column("hgvs_assay_level", sa.String(), nullable=True))
    op.add_column("mapped_variants", sa.Column("hgvs_g", sa.String(), nullable=True))
    op.add_column("mapped_variants", sa.Column("hgvs_c", sa.String(), nullable=True))
    op.add_column("mapped_variants", sa.Column("hgvs_p", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mapped_variants", "hgvs_p")
    op.drop_column("mapped_variants", "hgvs_c")
    op.drop_column("mapped_variants", "hgvs_g")
    op.drop_column("mapped_variants", "hgvs_assay_level")
    # ### end Alembic commands ###
