"""taxonomy_add_attributes

Revision ID: bede0ecf087a
Revises: da9ba478647d
Create Date: 2023-06-22 16:48:12.065262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bede0ecf087a'
down_revision = 'da9ba478647d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomies', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('taxonomies', sa.Column('has_described_species_name', sa.Boolean(), nullable=True))
    op.add_column('taxonomies', sa.Column('url', sa.String(), nullable=True))
    op.add_column('taxonomies', sa.Column('article_reference', sa.String(), nullable=True))
    op.alter_column('taxonomies', 'organism_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxonomies', 'organism_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('taxonomies', 'article_reference')
    op.drop_column('taxonomies', 'url')
    op.drop_column('taxonomies', 'has_described_species_name')
    op.drop_column('taxonomies', 'rank')
    # ### end Alembic commands ###
