"""Add gene name column to target accession definition

Revision ID: c6154dd7d9b9
Revises: 60103ad1cb5b
Create Date: 2023-10-04 17:00:42.960917

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c6154dd7d9b9"
down_revision = "60103ad1cb5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("target_accessions", sa.Column("gene", sa.String(), nullable=True))
    op.alter_column("target_accessions", "assembly", nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_accessions", "gene")
    op.alter_column("target_accessions", "assembly", nullable=False)
    # ### end Alembic commands ###
