"""drop functional range jsonb

Revision ID: c770fa9e6e58
Revises: 16beeb593513
Create Date: 2025-11-17 22:19:22.440742

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "c770fa9e6e58"
down_revision = "16beeb593513"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("score_calibrations", "functional_ranges_deprecated_json")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "score_calibrations",
        sa.Column(
            "functional_ranges_deprecated_json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
