"""add mapped hgnc name to targets

Revision ID: dcf8572d3a17
Revises: 00dab0f5f498
Create Date: 2025-12-12 17:32:40.147429

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dcf8572d3a17"
down_revision = "00dab0f5f498"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("target_genes", sa.Column("mapped_hgnc_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_genes", "mapped_hgnc_name")
    # ### end Alembic commands ###
