"""add gnomad variants association table

Revision ID: ec535fd72270
Revises: 79b28316dd0c
Create Date: 2025-06-17 08:42:17.728564

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec535fd72270"
down_revision = "79b28316dd0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gnomad_variants_mapped_variants",
        sa.Column("mapped_variant_id", sa.Integer(), nullable=False),
        sa.Column("gnomad_variant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gnomad_variant_id"],
            ["gnomad_variants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mapped_variant_id"],
            ["mapped_variants.id"],
        ),
        sa.PrimaryKeyConstraint("mapped_variant_id", "gnomad_variant_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gnomad_variants_mapped_variants")
    # ### end Alembic commands ###
