"""empty message

Revision ID: f11fd758436e
Revises: 988ca84c701b
Create Date: 2023-05-16 15:03:22.252545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11fd758436e'
down_revision = '988ca84c701b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_sets', 'method_text')
    op.drop_column('experiment_sets', 'short_description')
    op.drop_column('experiment_sets', 'title')
    op.drop_column('experiment_sets', 'abstract_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_sets', sa.Column('abstract_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experiment_sets', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experiment_sets', sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('experiment_sets', sa.Column('method_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
