"""Additional mapping columns

Revision ID: f36cf612e029
Revises: ec5d2787bec9
Create Date: 2024-08-21 16:06:06.793541

"""

from datetime import datetime

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f36cf612e029"
down_revision = "ec5d2787bec9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mapped_variants",
        sa.Column("vrs_version", sa.String(), nullable=True, server_default="1.3"),
    )
    op.add_column("mapped_variants", sa.Column("error_message", sa.String(), nullable=True))
    op.add_column(
        "mapped_variants",
        sa.Column(
            "modification_date",
            sa.Date(),
            nullable=False,
            server_default=sa.func.current_date(),
        ),
    )
    op.add_column(
        "mapped_variants",
        sa.Column(
            "mapped_date",
            sa.Date(),
            nullable=False,
            server_default=datetime.fromisocalendar(2024, 1, 1).date().strftime("%Y-%m-%d"),
        ),
    )
    op.add_column(
        "mapped_variants",
        sa.Column("mapping_api_version", sa.String(), nullable=False, server_default="0.0.0"),
    )
    op.add_column(
        "mapped_variants",
        sa.Column("current", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column(
        "mapped_variants",
        "pre_mapped",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "mapped_variants",
        "post_mapped",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )

    op.add_column(
        "target_genes",
        sa.Column("pre_mapped_metadata", postgresql.JSONB, nullable=True),
    )
    op.add_column(
        "target_genes",
        sa.Column("post_mapped_metadata", postgresql.JSONB, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mapped_variants",
        "post_mapped",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "mapped_variants",
        "pre_mapped",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_column("mapped_variants", "current")
    op.drop_column("mapped_variants", "mapping_api_version")
    op.drop_column("mapped_variants", "mapped_date")
    op.drop_column("mapped_variants", "modification_date")
    op.drop_column("mapped_variants", "error_message")
    op.drop_column("mapped_variants", "vrs_version")

    op.drop_column("target_genes", "pre_mapped_metadata")
    op.drop_column("target_genes", "post_mapped_metadata")
    # ### end Alembic commands ###
