"""empty message

Revision ID: f3c5817381f9
Revises: 9d566d915a2c
Create Date: 2022-11-21 22:31:04.021959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c5817381f9'
down_revision = '9d566d915a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('vocabulary', sa.String(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('modification_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'value', name='ix_controlled_keywords_key_value')
    )
    op.create_index(op.f('ix_controlled_keywords_id'), 'controlled_keywords', ['id'], unique=False)
    op.create_table('scoreset_controlled_keywords',
    sa.Column('scoreset_id', sa.Integer(), nullable=False),
    sa.Column('controlled_keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controlled_keyword_id'], ['controlled_keywords.id'], ),
    sa.ForeignKeyConstraint(['scoreset_id'], ['scoresets.id'], ),
    sa.PrimaryKeyConstraint('scoreset_id', 'controlled_keyword_id')
    )
    op.create_foreign_key(None, 'scoresets', 'scoresets', ['replaces_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scoresets', type_='foreignkey')
    op.drop_table('scoreset_controlled_keywords')
    op.drop_index(op.f('ix_controlled_keywords_id'), table_name='controlled_keywords')
    op.drop_table('controlled_keywords')
    # ### end Alembic commands ###
