"""remove score range property from score sets

Revision ID: f5a72192fafd
Revises: 002f6f9ec7ac
Create Date: 2025-10-08 15:35:49.275162

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f5a72192fafd"
down_revision = "002f6f9ec7ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoresets", "score_ranges")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoresets",
        sa.Column("score_ranges", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
