"""Add is_base_editor column to target_accessions

Revision ID: f69b4049bc3b
Revises: d6e5a9fde3c9
Create Date: 2025-03-02 14:06:52.217554

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f69b4049bc3b"
down_revision = "d6e5a9fde3c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "target_accessions", sa.Column("is_base_editor", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_accessions", "is_base_editor")
    # ### end Alembic commands ###
