class VariantPosition:
    def __repr__(self) -> str: ...
    def __lt__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def is_utr(self) -> bool: ...
    def is_intronic(self) -> bool: ...
    def is_protein(self) -> bool: ...
    def is_extended(self) -> bool: ...
    def is_adjacent(self, other: object) -> bool: ...
