version: 1
disable_existing_loggers: False

root:
  # Filtering of messages by level is done at the handler level by using NOTSET
  # on the root logger to emit everything.  This lets us keep console output
  # readable while emitting verbose output to alternate handlers.
  level: NOTSET
  propagate: true
  handlers:
    - console

loggers:
  urllib3:
    level: INFO

  botocore:
    level: INFO

  hgvs:
    level: WARNING

  # To log all database queries, set this to INFO
  sqlalchemy:
    level: WARNING

handlers:
  console:
    class: logging.StreamHandler
    level: !coalesce
      - !LOG_LEVEL
      - INFO
    stream: ext://sys.stdout
    formatter: json

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(message)s"
