import os

CLIN_GEN_SUBMISSION_ENABLED = os.getenv("CLIN_GEN_SUBMISSION_ENABLED", "false").lower() == "true"

GENBOREE_ACCOUNT_NAME = os.getenv("GENBOREE_ACCOUNT_NAME")
GENBOREE_ACCOUNT_PASSWORD = os.getenv("GENBOREE_ACCOUNT_PASSWORD")

CLIN_GEN_TENANT = os.getenv("CLIN_GEN_TENANT")

LDH_SUBMISSION_TYPE = "cg-ldh-ld-submission"
LDH_ENTITY_NAME = "MaveDBMapping"
LDH_ENTITY_ENDPOINT = "maveDb"  # for some reason, not the same :/

DEFAULT_LDH_SUBMISSION_BATCH_SIZE = 100
LDH_SUBMISSION_ENDPOINT = f"https://genboree.org/mq/brdg/pulsar/{CLIN_GEN_TENANT}/ldh/submissions/{LDH_ENTITY_ENDPOINT}"
LDH_ACCESS_ENDPOINT = os.getenv("LDH_ACCESS_ENDPOINT", "https://genboree.org/ldh")
LDH_MAVE_ACCESS_ENDPOINT = f"{LDH_ACCESS_ENDPOINT}/{LDH_ENTITY_NAME}/id"

LINKED_DATA_RETRY_THRESHOLD = 0.95
