from abc import ABC

class _DataProxy(ABC):
    def get_metadata(self, identifier: str) -> dict: ...
    def get_sequence(self, identifier: str, start: int | None = ..., end: int | None = ...) -> str: ...

class SeqRepoDataProxy(_DataProxy):
    def __init__(self, sr: object) -> None: ...
