from typing import Any, Iterator, Optional
import sqlite3

class SeqAliasDB(object):
    _db_path: str
    _db: sqlite3.Connection
    _writeable: bool
    _db_row_factory: sqlite3.Row

    def __init__(
        self,
        db_path: str,
        writeable: bool = False,
        translate_ncbi_namespace: Any = None,
        check_same_thread: bool = True,
    ) -> None: ...
    def __del__(self) -> None: ...
    def __contains__(self, seq_id: str) -> bool: ...
    def commit(self) -> None: ...
    def fetch_aliases(
        self, seq_id: str, current_only: bool = True, translate_ncbi_namespace: Any = None
    ) -> list[dict]: ...
    def find_aliases(
        self,
        seq_id: Optional[str] = None,
        namespace: Optional[str] = None,
        alias: Optional[str] = None,
        current_only: bool = True,
        translate_ncbi_namespace: Any = None,
    ) -> Iterator[dict]: ...
    def schema_version(self) -> int: ...
    def stats(self) -> dict: ...
    def store_alias(self, seq_id: str, namespace: str, alias: str) -> int: ...
    def _dump_aliases(self) -> None: ...
    def _upgrade_db(self) -> None: ...
